### ISSUE TITLE
Menubar always visible when using tiling WM

### ISSUE THREAD

**Issue by Chronody** [crmarsh/discord-linux-bugs#10]
![puush](https://cloud.githubusercontent.com/assets/13288944/14650575/aa003980-066c-11e6-8c65-6f64b38defcf.jpg)

Distro: Arch 4.5.0-1 64Bit
WM: AwesomeWM v3.5.9
(Even visible in Fullscreen mode)

**Comment by crmarsh** [comment]
Fixed in 0.0.3, I think.
