### ISSUE TITLE
System hang on connecting to a voice channel

### ISSUE THREAD

**Issue by HellishINC** [crmarsh/discord-linux-bugs#103]
Using discord-canary 0.0.9, joining any server's channel casues a complete system hang. This issue did not exsist in x.8 but I was having issue #16. This is on Arch x64 using Pulse. The program runs fine until I join a server (am able to change settings and the like).

The only output that discord gives before the hang is:

`DiscordCanary 0.0.9
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/helly/.config/discordcanary/0.0.9/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
Initializing voice engine [legacy device: false]`

I know this information is pretty useless, is there any arguments I could pass to make output more verbose? There is no manpage and --help/-h is ignored.

Is there any chance the tarball for 0.0.8 could be mirrored in the meantime?

**Comment by Waytipsy** [comment]
I have this same issue after upgrading from 0.0.8 to 0.0.9. I tried reverting back to 0.0.8 but the issue remained. Also tried removing the package,  deleting discord related folders in home and rebuilding from scratch with no luck.

**Comment by HellishINC** [comment]
I can confirm that downgrading and purging all files still results in the hang.

**Comment by Waytipsy** [comment]
Assuming I do have the same issue as old mate Hellish.

Discord-Canary was only hanging upon joining a voice server so I tried removing Pulseaudio and just running ALSA.

It works, well sort of. The latency is extremely high ~3000ms, far too high to be usable. If I run the web client in Chrome the latency is normal ~40ms for my main server but obviously the point is to run the app not the web client.

I prefer pure ALSA and DMIX over Pulseaudio anyway tbh but either is fine as long as I can use PTT so it can't be the web app.

**Comment by HellishINC** [comment]
That's issue #16. Sad to see that it was not fixed in 0.0.9.

**Comment by crmarsh** [comment]
Yeah, I'm aiming to fix #16 before going to PTB. I'm not sure what this hang might be yet.

**Comment by crmarsh** [comment]
I assume that is the description you meant?

**Comment by HellishINC** [comment]
That is correct though I have not tested direct calls as the few people I managed to convert have started jumping back due to not being able to use it.

**Comment by xpander69** [comment]
Same issue here on Arch x86_64. im using JACK audio through pulse with jack sink and source. worked fine with 0.0.8, upgraded to 0.0.9 and system hangs when connecting to voicechannels. downgraded to 0.0.8 and removed all the configs, cache and whatnot but the issue is still there.

**Comment by xpander69** [comment]
Seems the issue was with my ck kernel. went back to normal Arch kernel and everything seems to work fine.. 

if others can confirm this, then that can be closed and its probably some sort of weird bug in the ck patches

**Comment by HellishINC** [comment]
It does indeed seem to be the CK kernel. I'll close this for now unless Waytipsy states he is not.

**Comment by Waytipsy** [comment]
I am running CK Piledriver, won't be home from work for another 15hrs or so to test but sounds like the culprit. Thanks
