### ISSUE TITLE
Discord icon not showing on Plank anymore

### ISSUE THREAD

**Issue by Wolpharion** [crmarsh/discord-linux-bugs#106]
So I just saw that Discord Canary had a 0.0.9 update, and just installed it, but it seems like the update just broke its Plank icon (the dock at the bottom of the screen):
![screenshot at 2016-10-26 23 49 49](https://cloud.githubusercontent.com/assets/22259985/19746767/2d147efc-9bd8-11e6-8e43-cdd8b61c9bac.png)

Here's what I had with 0.0.8, it worked perfectly:
![screenshot at 2016-10-26 23 54 59](https://cloud.githubusercontent.com/assets/22259985/19746790/4bec9260-9bd8-11e6-95d2-d3ec72a8a053.png)

I think it may be linked with the splash screen change, as the said Discord icon appears during the loading, and then disappears when the app is fully loaded.

I'm running on Ubuntu MATE, if you need this information:
![screenshot at 2016-10-27 00 01 41](https://cloud.githubusercontent.com/assets/22259985/19746861/9304232a-9bd8-11e6-890f-bf2960ae331c.png)

**Comment by Wolpharion** [comment]
Ok so, by magic, it fixed itself. I didn't understand. I guess it's closed then.

**Comment by crmarsh** [comment]
Huh. Okay. I'm still curious what I might have messed up there, but I guess eventually working is better than not working.

**Comment by Wolpharion** [comment]
Well, I don't know. x) Maybe it was a little bug on Plank's side, after all, I haven't encountered the problem anymore. Sorry for the inconvenience.

**Comment by thetarkus** [comment]
This happens when you launch it. The splash/loading screen makes the icon appear in Plank, but when the main window appears the icon disappears.

If anyone is still having this problem:
The workaround is to close the main window and then re-open with the icon in the systray.
