### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by viggou** [crmarsh/discord-linux-bugs#109]
There is a lot of visual bugs. I use both Debian and Kali.
Everything else is working just fine 👍

**Comment by shaggytwodope** [comment]
"Visual bugs" is not very helpful to anyone as it describes very little. More details, commit used, and even screenshots can help track down issues better.

**Comment by crmarsh** [comment]
This forum really only works for specific bugs; feel feel to open up bugs that describe in more detail what's going on.
