### ISSUE TITLE
Useless update button

### ISSUE THREAD

**Issue by sn0w** [crmarsh/discord-linux-bugs#110]
Discord shows the "Update available" button but clicking it only shows the PC/OSX links.

![screenshot from 2016-10-28 23-52-54](https://cloud.githubusercontent.com/assets/5665732/19823611/d609ebfe-9d69-11e6-8110-528ec153a13f.png)
![screenshot from 2016-10-28 23-53-08](https://cloud.githubusercontent.com/assets/5665732/19823614/d8ba8656-9d69-11e6-9b16-c2153de6ba91.png)

**Comment by viggou** [comment]
I have that issue too.

**Comment by greenbigfrog** [comment]
everyone has that issue... and once there is a "PTB" or actual public release it will work...

**Comment by crmarsh** [comment]
This is just to let you know there is an update. Download page doesn't have a linux build because we have not shipped one yet in the stable or PTB channels, which is what the download page points to.
