### ISSUE TITLE
OBS Studio isn't detected (to enable Streamer Mode)

### ISSUE THREAD

**Issue by ThePooN** [crmarsh/discord-linux-bugs#111]
OBS Studio isn't detected and Streamer Mode isn't triggered automatically, even though the option is enabled.
The process name is, simply, `obs`.

**Comment by crmarsh** [comment]
I'll add that in

**Comment by crmarsh** [comment]
It's a JS change; will go out the next time we deploy that stuff.

**Comment by ThePooN** [comment]
Nice :+1:

**Comment by ThePooN** [comment]
Working, for a week already, forgot to confirm.
