### ISSUE TITLE
32 Bit Discord Architecture would be nice if you think it's worth the time and the effort!

### ISSUE THREAD

**Issue by grunge197** [crmarsh/discord-linux-bugs#114]
Just a thought, because some of us Linux users use 32 bit architectures. I couldn't install the package because it has a 64 bit architecture, and mind you; I'm a bit of a noob to linux... so I could be missing something

**Comment by crmarsh** [comment]
There is further discussion of this in #56, but tldr: you probably want to be running a 64-bit system if your CPU supports it, and if it is less than 10 years old it almost certainly does.
