### ISSUE TITLE
"Toggle menu bar" option

### ISSUE THREAD

**Issue by rgiyf** [crmarsh/discord-linux-bugs#124]
Please make an option to toggle menubar like in Atom. On non-Unity DE's it's look like this:
![screenshot from 2016-11-05 17 33 07](https://cloud.githubusercontent.com/assets/9195693/20030835/f543a7de-a37d-11e6-83b4-febd8632f822.png)
I think you need this http://electron.atom.io/docs/api/browser-window/#class-browserwindow
`autoHideMenuBar Boolean - Auto hide the menu bar unless the Alt key is pressed. Default is false`

**Comment by crmarsh** [comment]
I used to have that, but it seemed worse. TBH, we don't really have much that is worthwhile in the menu bar; we mostly just put things there as a simple way to register the keyboard shortcuts.

**Comment by rgiyf** [comment]
I thought you did something because for a few days i don't have that in elementary. Anyway thanks!

**Comment by jmfgdev** [comment]
My issue is i've enabled this menu bar by accident now and i don't know how to hide it, im using Ubuntu
