### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by namirsab** [crmarsh/discord-linux-bugs#13]
```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at SplashWindow.focus (/usr/share/discord-canary/resources/app.asar/app/SplashWindow.js:66:27)
    at /usr/share/discord-canary/resources/app.asar/app/index.js:611:22
    at Socket.<anonymous> (/usr/share/discord-canary/resources/app.asar/app/singleInstance.js:59:7)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

**Comment by crmarsh** [comment]
As of 0.0.3, nothing should be using SplashWindow -- are you sure you are on the latest version?

**Comment by GreyAsteroid** [comment]
Running on 0.0.3, also having this issue on Ubuntu.

**Comment by namirsab** [comment]
I have 0.3 in Ubuntu 15
It didn't, happen with 0.2 though

**Comment by crmarsh** [comment]
I'm like 99% sure you are not actually running 0.0.3. I'm adding a thing to print the version number in 0.0.4, so I'll say it is fixed there.

**Comment by GreyAsteroid** [comment]
After purging the package and deleting all folders having to do with Discord, reinstalling the same 0.0.3 deb and restarting my computer this morning I was able to get it running again without that error showing up. 100% 0.0.3 however it seemed to be an issue upgrading from 0.0.2 to 0.0.3

**Comment by namirsab** [comment]
@crmarsh I did the same as @GreyAsteroid and everything is working now. The problem was updating from 0.0.2 to 0.0.3

**Comment by crmarsh** [comment]
Cool. Sorry, I'm still learning how to CDN, I guess.
