### ISSUE TITLE
Avatar removed after changing username

### ISSUE THREAD

**Issue by GlennVanSchil** [crmarsh/discord-linux-bugs#134]
Steps:
- Change username
- Enter current password
- Click done

After doing these steps my avatar was reset to the default avatar

**Comment by crmarsh** [comment]
This is more of a server side bug, but I passed it along to the folks that work on that.

**Comment by jhgg** [comment]
Looks like this was a bug with our server-side code. A fix is coming out soon.

**Comment by crmarsh** [comment]
This was fixed a while back
