### ISSUE TITLE
FATAL:nss_util.cc(203)] nss_error=-5925, os_error=0

### ISSUE THREAD

**Issue by funghetto** [crmarsh/discord-linux-bugs#136]
I'm trying to start it on Slackware but I get this output:

`bash-4.3$ ./DiscordCanary 
DiscordCanary 0.0.11
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/zeno/.config/discordcanary/0.0.11/modules
[1797:1120/154151:FATAL:nss_util.cc(203)] nss_error=-5925, os_error=0
#0 0x000000c1409e <unknown>
#1 0x000000c2a91b <unknown>
#2 0x000002d13838 <unknown>
#3 0x00000091560b <unknown>
#4 0x000000968387 <unknown>
#5 0x000000916edb <unknown>
#6 0x00000351de48 atom::AtomCertVerifier::AtomCertVerifier()
#7 0x000003505abc atom::AtomBrowserContext::CreateCertVerifier()
#8 0x00000359fc7c brightray::URLRequestContextGetter::GetURLRequestContext()
#9 0x0000015cc64c <unknown>
#10 0x0000018f1df1 <unknown>
#11 0x000000c14f56 <unknown>
#12 0x000000c30e15 <unknown>
#13 0x000000c31108 <unknown>
#14 0x000000c3155b <unknown>
#15 0x000000c0a1a9 <unknown>
#16 0x000000c4a49e <unknown>
#17 0x000000c69b8a <unknown>
#18 0x000001601416 <unknown>
#19 0x00000160161e <unknown>
#20 0x000000c69c4e <unknown>
#21 0x000000c66063 <unknown>
#22 0x7efc0b68a684 start_thread
#23 0x7efc0514fefd __clone

Failed to get crash dump id.
Report Id: 
Aborted`

**Comment by funghetto** [comment]
I fixed it upgrading NSS from the Slackware version [3.23] to the current stable release[3.27.1].

**Comment by crmarsh** [comment]
Cool, glad you figured it out 👍
