### ISSUE TITLE
Empty dark gray page

### ISSUE THREAD

**Issue by funghetto** [crmarsh/discord-linux-bugs#138]
After the twirling gamepad the window displays just an empty dark gray page if I do not run it as root.

bash-4.3$ ./DiscordCanary
DiscordCanary 0.0.11
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/zeno/.config/discordcanary/0.0.11/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
Initializing voice engine [legacy device: false]
0: [+] Entered: WorkerThreadMain
1: [+] Entered: Initialize
1: [-] Exited: Initialize
did-fail-load https://canary.discordapp.com/channels/@me?_=1479827436916 -2 ERR_FAILED

**Comment by crmarsh** [comment]
Do you need to be root to access the network?

**Comment by funghetto** [comment]
What do you mean?

Other applications (browsers, steam, wget...) can access the network without root permission.

**Comment by crmarsh** [comment]
I mean, you got an error that you couldn't connect to our server, and you said it works if you run as root. There is nothing I'm aware of that should require root access in Discord, it was just the first question that came to mind.

**Comment by funghetto** [comment]
It works fine with a fresh install... How did I mess up?
