### ISSUE TITLE
More noticeable alert icon for tray icon

### ISSUE THREAD

**Issue by ShayBox** [crmarsh/discord-linux-bugs#139]
Maybe a better alert indication on the tray icon, a purple dot blends in to my dark task bar too much and i have to get really close to see if its there or not, maybe change his eyes to yellow/red/green or the entire icon could have a glow around it, not sure. but something that works well in dark/light themes.

[Without alert](https://gyazo.com/a10e2eceef5a75bfd399ce6e1b783503)
[With alert](https://gyazo.com/e6b28948c384aa1e028d05c04f1f72f9)

**Comment by crmarsh** [comment]
I agree with you; though in my use case, I basically never see an unread version of that icon, so it's not very high priority (for me anyway).

We have plans (some of which the work is mostly done for I think?) for using some more colors there for different states, so I'm at least gonna wait for that to finish up before tweaking anything. Maybe they already addressed this, I'm not sure.
