### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Daverball** [crmarsh/discord-linux-bugs#14]
OpenSUSE Leap 42.1, Kernel 4.1.15, KDE/Plasma 5

I'm seeing extremely high CPU usage ~80% of a single core on an Intel i7-4820k with Hyper Threading turned off

**Comment by crmarsh** [comment]
I'm not seeing anything unusual on my machines :-/

**Comment by Daverball** [comment]
Alright, after some fiddling around I figured out the cause. If pulseaudio is running the CPU usage is normal, if however only alsa is present the high CPU usage occurs. So my best guess would be that the application just keeps on polling for a pulseaudio server which causes the high CPU usage.

**Comment by crmarsh** [comment]
I'm going to close this out and refer you to [16](https://github.com/crmarsh/discord-linux-bugs/issues/16)
