### ISSUE TITLE
All audio except voices playing

### ISSUE THREAD

**Issue by BytewaveMLP** [crmarsh/discord-linux-bugs#140]
(**NOTE:** Using the unofficial `discord-canary` package on the Arch AUR, but that just downloads the `.tar.xz` anyway)

After a system update, I've been noticing a strange issue where I can't hear anyone talking in Discord. The PulseAudio handle seems to completely disappear after 10 seconds or so, and only reappears for sound effects, not voices. I'm not sure what exactly changed in the last batch of package updates, as I didn't keep track, but I know a lot of `gst`/`gstreamer` packages updated, if that matters.

The green circles indicating voice activity do **not** appear around clients' icons when they speak, either, if that matters. The web version of the client works, and the Windows client also seems to work fine. Repeated reboots do nothing.

**Comment by WinSuk** [comment]
I'm having the same problem (also on Arch), but I have not updated gstreamer/gst yet - that's still version 1.10.1 that I installed on November 19th. Discord has been working fine until now and I haven't updated or changed anything.

**Comment by Shorty-06** [comment]
Having the exact same issue on Ubuntu 16.10. I've reinstalled the official `discord-canary` package multiple times (including deleting the config files manually which) `sudo apt purge` doesn't seem to remove. There's no errors when run from the terminal, in the application, or when using the console (`ctrl + shift + i`). In the voice debug settings there's no errors either, but in the users section every user is showing as having sent 0 bytes to me.

Also worth mentioning is that this seems to be an issue with the application specifically. On both the web and mobile apps on the same network I can hear users fine. The web app works on the same computer.

I can't hear users in channels or in calls, and I can't hear bots in channels either.

**Comment by creeperlwd** [comment]
i'm having the same issue (no green circles, everyone can hear me fine etc.)

**Comment by funghetto** [comment]
Same as creeperlwd.

**Comment by cryzed** [comment]
Same here, also appeared after updating gstreamer and related packages on an Arch Linux system:

```
[2016-11-30 00:14] [ALPM] upgraded gstreamer (1.10.1-1 -> 1.10.2-1)
[2016-11-30 00:14] [ALPM] upgraded gst-plugins-base-libs (1.10.1+1+g1f4da6d-1 -> 1.10.2-1)
[2016-11-30 00:14] [ALPM] upgraded gst-plugins-bad (1.10.1-1 -> 1.10.2-1)
[2016-11-30 00:14] [ALPM] upgraded gst-plugins-base (1.10.1+1+g1f4da6d-1 -> 1.10.2-1)
[2016-11-30 00:14] [ALPM] upgraded gst-plugins-good (1.10.1-1 -> 1.10.2-1)
[2016-11-30 00:14] [ALPM] upgraded gst-plugins-ugly (1.10.1-1 -> 1.10.2-1)
```

**Comment by ussian** [comment]
Same here on ubuntu 16.04 lts

**Comment by Cardbeat** [comment]
same here on ubuntu 14.04 lts

**Comment by crmarsh** [comment]
Yeah, this is all kinds of broken atm (on Windows canary too). There was a JS change that needs a client side change that is not out yet.

**Comment by crmarsh** [comment]
It should be working again.

**Comment by Shorty-06** [comment]
Yup, I can hear people again now, thanks for the fix!

**Comment by sKreevA4** [comment]
Having a similar problem, not aware if this is the same bug.
