### ISSUE TITLE
No sound input on desktop version [bug]

### ISSUE THREAD

**Issue by VoxSomniator** [crmarsh/discord-linux-bugs#142]
Discord canary on ubuntu doesn't get any sound input- I've confirmed that the system is receiving sound from the microphone, and other programs can get it, but no combination of settings will get Discord to work. I've reinstalled and reset settings three or four times on both systems. The browser version gets sound just fine, at least.

I can hear other people in voice chat, but they can't hear me, and the bar for changing the voice threshhold in settings doesn't show any sound at all.

Tested with USB headset+microphone, separate aux-cord headset and microphones, on two totally different systems. No change at all.

Using Ubuntu 16.04 LTS. Is there any other information I could provide that would be helpful?

![selection_001](https://cloud.githubusercontent.com/assets/24360931/20862391/ed8694f2-b976-11e6-9d95-d29144d82094.png)
Taken while blowing into the microphone. Orange bar in system settings indicates the sound is getting through, no input options for discord work.

**Comment by AntonBoch1244** [comment]
@VoxSomniator, try use only ALSA and watch in settings. Discord Canary looping sound.

**Comment by red-bin** [comment]
I had the same issue - looks like Discord isn't opening an audio stream while in this screen, which it should be doing - probably even at application startup. The issue went away after joining a voice channel.

**Comment by crmarsh** [comment]
I see what you were talking about now. Yeah, we don't gather mic input until you join a voice channel. I agree it is a little confusing if the first thing you do is jump into the voice config panel. This is not really Linux specific, it's just how we set up that screen on all platforms.

**Comment by VoxSomniator** [comment]
@red-bin and @crmarsh Sorry for being unclear, but there is no change when I'm in a voice channel. Nobody is ever able to hear me outside of the browser version.

@AntonBoch1244 what do you mean? Disable pulseaudio so ALSA is running without it? That seems like it would break far more things than it would fix.
