### ISSUE TITLE
Running "killall DiscordCanary" destroys the entire UI session

### ISSUE THREAD

**Issue by JaneSmith** [crmarsh/discord-linux-bugs#146]
I tested this on Ubuntu 16.10 with the latest version of Discord. It happened for me consistently, multiple times, so it's very reproducible (at least for me).

**Steps to reproduce:**

1. Run Discord.
2. Open a terminal.
3. Run `killall DiscordCanary`.

**Expected result:**

- Discord should close.

**Actual result:**

- The Discord window starts to "pulse" as if it's either opening and closing over and over again, or loading new instances in the same location over and over again.
- The Unity launcher shows more and more Discord icons as time passes.
- The system quickly gets slower and slower until it freezes entirely.
- The UI session crashes and restarts, killing all other GUI applications and losing any data they might have had.

**Comment by crmarsh** [comment]
Oh weird, I thought I had fixed that :-/

**Comment by tortue-mine** [comment]
Here's a sleek `.gif` to see what happens with `dwm` on Arch Linux with the latest version as well:
![`dwm` having seizures](https://i.imgur.com/6W9IbYt.gifv)

This is my only way to close Discord properly using a window manager in general, since I don't use a system tray.

Fun.

**Comment by crmarsh** [comment]
You can just Ctrl-q to quit if you want. That said, I have a fix for this coming in the next build.

**Comment by crmarsh** [comment]
Fixed in 0.0.12
