### ISSUE TITLE
Editing a message while deleting makes it edit in the delete window

### ISSUE THREAD

**Issue by ArsenArsen** [crmarsh/discord-linux-bugs#148]
![Bug](http://i.imgur.com/VwBwSlB.png)
# Steps to reproduce:
Right click
Press `Delete Message`
Press `UP ARROW`

**Comment by ArsenArsen** [comment]
This leads to a bigger problem, the modals don't take the control of keybindings, but the chat does. It is currently impossible to delete a message by pressing `RETURN` or `ENTER`

**Comment by crmarsh** [comment]
Seems to be fixed.

**Comment by ArsenArsen** [comment]
Thanks, I'll try it and re open if needed 

Have a good day 😃
