### ISSUE TITLE
OAuth2 and Twitch Integration Auth Errors

### ISSUE THREAD

**Issue by ryan77627** [crmarsh/discord-linux-bugs#149]
Discord doesn't want to connect to Youtube or Twitch for some reason. For Youtube, it gives me this:

Error: redirect_uri_mismatch

The redirect URI in the request, https://canary.discordapp.com/api/connections/youtube/callback, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/162066849712-q6t4kc4ln13ac3eq4sa01gpb8k715bjc.apps.googleusercontent.com?project=162066849712 to update the authorized redirect URIs.

And Twitch gives me the same errors.

I am running Discord Canary on Ubuntu 16.10.

**Comment by crmarsh** [comment]
This is because we never set this stuff up to work in our Canary builds -- it will work on the stable build when that is available, and in the mean time you can set this up with the browser version.
