### ISSUE TITLE
discord canary going blank after opening (manjaro linux)

### ISSUE THREAD

**Issue by blyatman66** [crmarsh/discord-linux-bugs#158]
when i try to open discord now i just get this. it worked perfectly up until today
![discord](https://cloud.githubusercontent.com/assets/22215004/21579810/47d8ac1a-cfbb-11e6-93e7-c70a28ea6580.png)

**Comment by llldino** [comment]
I'm having the same problem here.

`$ uname -a`
`Linux pimr15 4.8.0-0.bpo.2-amd64 #1 SMP Debian 4.8.11-1~bpo8+1 (2016-12-14) x86_64 GNU/Linux`

**Comment by dahjin** [comment]
Same problem on Arch.

**Comment by daniel-Jones** [comment]
Same problem, from console:

Using update channel 'canary'
Fetching https://discordapp.com/api/modules/linux/canary/versions.json
did-fail-load  -501 
^C7882: [-] Exited: WorkerThreadMain

**Comment by SSStormy** [comment]
Same problem on Arch.

```
[~] uname -a
Linux justas-main 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

Works fine on win7 x64.

**Comment by Hugo14453** [comment]
I believe... this is due to the expired certificate with the Discord Website and not a Canary issue, the web based version is also giving weird issues.

**Comment by SomaUlte** [comment]
also happened to me just a few minutes ago
~ uname -a
Linux ODIN 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

when running from console
did-fail-load https://canary.discordapp.com/channels/@me?_=1483233033838 -501 ERR_INSECURE_RESPONSE

**Comment by SSStormy** [comment]
Yeah the certificate most definitely expired:

```
canary.discordapp.com uses an invalid security certificate. The certificate expired on 01/01/2017 01:59 AM. The current time is 01/01/2017 03:12 AM.
```

**Comment by SomaUlte** [comment]
certs back :D

**Comment by blyatman66** [comment]
yay. thanks for letting us know

**Comment by yurytch** [comment]
Having a similar issue now. Gray-blank screen, no errors shown in console, tpcdump shows some activity involving certificates on port 443 initially, then nothing substantial, several sockets are open to ports 443 (one of those is constantly closing and reopening to a new IP), one socket open to port 80, like follows. The $HOME/.pki erased and re-created. Any advise?

216.58.214.206:443      ESTABLISHED
35.188.42.15:443        CLOSE_WAIT
104.16.11.231:443       ESTABLISHED
172.217.20.206:80       ESTABLISHED
172.217.20.174:443      ESTABLISHED

**Comment by IGJoshua** [comment]
I'm still seeing this issue on manjaro linux with XFCE.
```
[j<REDACTED>@joshua-linux-pc ~]$ uname -a
Linux joshua-linux-pc 4.13.4-1-MANJARO #1 SMP PREEMPT Wed Sep 27 16:24:43 UTC 2017 x86_64 GNU/Linux
```

I've been seeing this issue for several months at this point, but didn't think much of it since the web version works just fine for me.

Console output:
```
Discord 0.0.2
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/jsuskalo/.config/discord/0.0.2/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
```
And finally a screenshot:
![discord-0 0 2](https://user-images.githubusercontent.com/27734541/31918000-6eacbd08-b828-11e7-9906-10ee0c5333b2.png)

If anyone has suggestions for how to fix this it would be greatly appreciated!

**Comment by yurytch** [comment]
Install the clang's libc++ (may go under the libcxx name). This isn't well advertised in solutions, but actually fixed the issue for me.

**Comment by ualvesdias** [comment]
Installing libcxx worked for me on Fedora 26! Thanks!!!
