### ISSUE TITLE
duplicate: canary.discord.com ssl cert expired

### ISSUE THREAD

**Issue by skipperblue** [crmarsh/discord-linux-bugs#159]
When opening Discord Canary the window is just blank. I tried purging and reinstalling but that did not help. Running the application from terminal gives this output:
DiscordCanary 0.0.11
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/sb/.config/discordcanary/0.0.11/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
Initializing voice engine [legacy device: false]
did-fail-load https://canary.discordapp.com/channels/@me?_=[SNIP] -501 ERR_INSECURE_RESPONSE

When trying to access that url from firefox I also get a warning saying that the security certificate has expired. "The certificate expired on 12/31/2016 06:59 PM. The current time is 12/31/2016 08:05 PM."

additionally, the web client works, but i cannot see server icons or user avatars. I assume that is an issue for someone else though.

**Comment by crmarsh** [comment]
Dupe, and is fixed now.
