### ISSUE TITLE
Discord says update available, on linux, cant update.

### ISSUE THREAD

**Issue by Nackloose** [crmarsh/discord-linux-bugs#162]
Discord says update available, and the client seems to be acting rather glitchy, images, aren't loading, etc, chat is very slow, and laggy. When I try to update it brings me to a white popup page where discord is labeled as coming soon, on both the public test build and the stable build.
I've tried updated the client by right clicking the icon, but instead of closing discord and stating an update progress bar, it simply opens the same white window(shown below)
![image](https://cloud.githubusercontent.com/assets/8534886/21627279/cb1203e6-d1ba-11e6-8904-d186c984b6ab.png)
I'd really appreciate some sort of fix or work around for this.

**Comment by crmarsh** [comment]
We have not released the PTB or stable build yet or updated the download page to have a link. For now, you need to manually install the canary build again. I put links to the packages [here](https://github.com/crmarsh/discord-linux-bugs)
