### ISSUE TITLE
Discord is updated but still asks to have update installed

### ISSUE THREAD

**Issue by somaulte** [crmarsh/discord-linux-bugs#163]
On Arch my pacman lists version as 
>discord-canary 0.0.13-1

yet when opening the app it shows the "must be your lucky day" screen with links for downloads.

**Comment by GitBranch** [comment]
I do have this issue too... However I am on manjaro, which uses the same AUR packages.
This shows up when I try to start it from the terminal:
```
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x3a43262157a0)" of type `gboolean'
DiscordCanary 0.0.11
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/omicron/.config/discordcanary/0.0.11/modules
[Modules] No updates to install
[Modules] Checking for host updates.
update: you are out of date!
[Modules] Host update is available. Manual update required!
```
What concerns me is the "DiscordCanary 0.0.11" part. The AUR package itself might be broken, but I'm not sure.

It pulls `https://dl-canary.discordapp.net/apps/linux/0.0.13/discord-canary-0.0.13.tar.gz` and I can confirm that that is working without asking me for an update.

**Comment by manulaiko** [comment]
I had same issue, fixed it with uninstalling it and reinstalling. Probably was because of BetterDiscord.

**Comment by SomaUlte** [comment]
I've uninstalled, purged all files, purged all betterdiscord files, reinstalled and still getting the update message :/

**Comment by ensiform** [comment]
I believe this is because discord on Linux uses electron/chromium which is basically serving up the web page version?  Not entirely sure on that.

**Comment by XNBlank** [comment]
@ensiform Discord uses a modified electron binary on all desktop platforms.

**Comment by ErmanSayin** [comment]
also having this problem on 0.0.17

**Comment by crmarsh** [comment]
I finally found out, this is from having extracted the asar locally; Discord tries to load files from outside the asar first, so having files there is overwriting the new version you install. This is how BetterDiscord works, I guess? Anyway, this bug falls in the 'stop hitting yourself' category. Delete the `resource/app` dir and you should be good to go.
