### ISSUE TITLE
Blank screen on Linux Mint

### ISSUE THREAD

**Issue by LEGOlord208** [crmarsh/discord-linux-bugs#167]
Oioi! Basically like the title said. Worked perfectly on Ubuntu and earlier today on Linux Mint. Might as well be temporary :/

![image](https://cloud.githubusercontent.com/assets/12830969/21684127/c417382e-d35c-11e6-87f4-b7f93b26b2b3.png)

**Comment by ensiform** [comment]
It went away for me eventually after it happened the other day.

**Comment by LEGOlord208** [comment]
Yeah, I reinstalled mine. Doesn't seem like a serious issue

**Comment by crmarsh** [comment]
That looks a lot like what happens with network errors on start up, which we don't yet handle with retries as you might expect.

**Comment by LEGOlord208** [comment]
The only thing is that restarting it didn't work... Only reinstalling D:

**Comment by crmarsh** [comment]
I fixed this a while back, forgot to post here.
