### ISSUE TITLE
Popup Dialogs Should Use Respect Theme Color Selection

### ISSUE THREAD

**Issue by erockce** [crmarsh/discord-linux-bugs#170]
Version: Canary 0.0.13
Distro: Ubuntu 16.0.4.1 x86_64

Currently the pop-up dialog boxes' (such as in Options, context menus, and user profiles) main text areas use white background with dark color lettering.  For consistency the colors should be similar to the selected dark theme.

I thought possibly there was a change in configuration since the past few releases so I changed the theme from dark to light then back to dark, and from Compact to Cozy to Compact but this had no effect.  Re-login also there was no change.

**Comment by crmarsh** [comment]
I kinda agree, but this is not a bug, this is how it was designed.

**Comment by erockce** [comment]
Future enhancement then?
