### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ZallionTDE** [crmarsh/discord-linux-bugs#175]
Started Discord, got the latest update automatically. Went to start new automatic update search on application run, got an exception error. Just updated Java 8, started it again. Same issue. Information to follow:

Error 
> ### A JavaScript error occurred in the main process
> Uncaught exception:
> Error: libc++.so.1: cannot open shared object file: No such file or directory
>    at Error (native)
>    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
>    at Object.Module._extensions..node (module.js:583:18)
>    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
>    at Module.load (module.js:473:32)
>    at tryModuleLoad (module.js:432:12)
>    at Function.Module._load (module.js:424:3)
>    at Module.require (module.js:483:17)
>    at require (internal/module.js:20:19)
>    at Object.<anonymous> (/home/nsharp/.config/discordcanary/0.0.13/modules/discord_voice/index.js:1:98)
>    at Module._compile (module.js:556:32)
>    at Object.Module._extensions..js (module.js:565:10)
>    at Module.load (module.js:473:32)
>    at tryModuleLoad (module.js:432:12)
>    at Function.Module._load (module.js:424:3)
>    at Module.require (module.js:483:17)
>    at require (internal/module.js:20:19)
>    at Object.<anonymous> (/usr/share/discord-canary/resources/app.asar/VoiceEngine.js:7:22)
>    at Module._compile (module.js:556:32)
>    at Object.Module._extensions..js (module.js:565:10)
>    at Module.load (module.js:473:32)
>    at tryModuleLoad (module.js:432:12)
>    at Function.Module._load (module.js:424:3)
>    at Module.require (module.js:483:17)
>    at require (internal/module.js:20:19)
>    at launchMainAppWindow (/usr/share/discord-canary/resources/app.asar/index.js:477:26)
>    at SplashWindow.<anonymous> (/usr/share/discord-canary/resources/app.asar/index.js:608:16)
>    at SplashWindow.g (events.js:286:16)
>    at emitNone (events.js:86:13)
>    at SplashWindow.emit (events.js:185:7)
>    at SplashWindow._launchMainWindow (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:255:14)
>    at Modules.<anonymous> (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:64:15)
>    at emitThree (events.js:121:20)
>    at Modules.emit (events.js:194:7)
>    at /usr/share/discord-canary/resources/app.asar/common/Modules.js:331:110
>    at _combinedTickCallback (internal/process/next_tick.js:67:7)
>    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```
uname -snrvpio
Linux hcwkn31 4.4.0-59-lowlatency #80-Ubuntu SMP PREEMPT Fri Jan 6 21:04:05 UTC 2017 x86_64 x86_64 GNU/Linux
```

```
dpkg -l discord-canary
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-============================================================
ii  discord-canary              0.0.13             amd64              All-in-one voice and text chat for gamers
```

```
dpkg -l openjdk-8-jre
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-============================================================
ii  openjdk-8-jre:amd64         8u121-b13-0ubuntu1 amd64              OpenJDK Java runtime, using Hotspot JIT
```

If you need anymore information, please let me know.

**Comment by SapphireTactician** [comment]
Duplicate of #174 . Beat you to this one, fam.

**Comment by ZallionTDE** [comment]
As per SapphireTactician's comment, closed as duplicate.
