### ISSUE TITLE
app crashes loading library after forced update to discord-canary-0.0.15

### ISSUE THREAD

**Issue by combusterf** [crmarsh/discord-linux-bugs#179]
![discordcanary-update](https://cloud.githubusercontent.com/assets/8459776/22395186/6e93f338-e536-11e6-9ba8-6fa79053f0d6.png)

Considering the reference to .config, I tried clearing it but that didn't resolve the issue

**Comment by skwerlman** [comment]
You need to install libc++. See #177 #175
