### ISSUE TITLE
Titlebars Missing on KDE Plasma 5.6.3

### ISSUE THREAD

**Issue by Mario3D13** [crmarsh/discord-linux-bugs#18]
Canary 0.0.3 lacks titlebars for KDE Plasma.

KDE Plasma Version: 5.6.3
KDE Frameworks Version: 5.21.0
Qt Version: 5.6.0

OS: Antergos Linux (Arch)
Linux Kernel Version: 4.5.1-1-ARCH

![screenshot_20160422_165300](https://cloud.githubusercontent.com/assets/10915337/14755874/e74a26f8-08aa-11e6-9742-b7900f2e089a.png)

**Comment by sarnex** [comment]
I'm on 5.6.3 and I see the titlebar.

**Comment by urbels** [comment]
KDE Neon:
Plasma 5.6.90
KDE: 5.21.0
Qt: 5.5.1

Not worked in 0.0.2 but now it works in latest 0.0.4.

**Comment by ahjolinna** [comment]
why is this still open?

**Comment by crmarsh** [comment]
I was hoping @Mario3D13 would chime back in if it was working for him now; if not I still have some kind of bug here.
