### ISSUE TITLE
Bad Request (reddit.com) when linking account. Canary 0.0.15

### ISSUE THREAD

**Issue by SapphireTactician** [crmarsh/discord-linux-bugs#181]
When attempting to link a Reddit account on the `Connections` tab of `User Setting`, I receive the following error page / message from Reddit:

```
bad request (reddit.com)

you sent an invalid request
— invalid redirect_uri parameter.
```

**Comment by SapphireTactician** [comment]
I found a workaround for now. The url used when linking an account includes `canary.discordapp.com` removing the `canary.` portion fixes it.

**Comment by ahjolinna** [comment]
it seems this also affects youtube, and it was "fixed" the same way

**Comment by SapphireTactician** [comment]
Probably applies to all account, I'd assume it'd be the same for Twitch too.

**Comment by ahjolinna** [comment]
yeah it applies to twitch also but not twitter, it worked just fine for me

**Comment by crmarsh** [comment]
Yeah, none of the account linking things work (or probably ever will work) with anything but the stable build and/or website. They are just a one time setup thing, though.

**Comment by SapphireTactician** [comment]
I know this is a rolling release and all, but you can at least TRY to not make it user hostile instead of closing these as won't fix. Just saying.

**Comment by crmarsh** [comment]
This doesn't have anything to do with the release schedule or method, and this isn't really a thing you can fix in code, or I would have. This is some OAuth setup on the other peoples' servers were you need to tell them which of your servers will be doing the asking... at least that's my understanding of it.

**Comment by SapphireTactician** [comment]
I see, my apologies. I thought the `.canary` part of the `redirect_uri` was baked into the application under some version information string or something.
