### ISSUE TITLE
Canary cant connect to any 3rd party services. mismatched-uri

### ISSUE THREAD

**Issue by Nackloose** [crmarsh/discord-linux-bugs#189]
All of the services redirect to the pages for [Twitch](https://discordapp.com/connections/twitch?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI),
Youtube 
[![image](https://cloud.githubusercontent.com/assets/8534886/22612725/9e7596d0-ea16-11e6-8a1b-d3a5677f07f4.png)](https://console.developers.google.com/apis/credentials/oauthclient/162066849712-q6t4kc4ln13ac3eq4sa01gpb8k715bjc.apps.googleusercontent.com?project=162066849712)
link is to url in picture
reddit, and twitter, all say mismatched application url for authentications coming from the canary.discordapp.com domain. Pls can haz account connections.
Im pretty sure this used to work, cause I know I looked at it before, but its 100% borked right now, so my best guess is someone botched a copy paste job somewhere, or something.
Or maybe Im mad and it never worked. Either way:
![image](https://cloud.githubusercontent.com/assets/8534886/22612818/33ce03f2-ea17-11e6-8539-33ee34dc2ade.png)

**Comment by crmarsh** [comment]
Yeah, canary and ptb don't work for that stuff, you'll need to use the website to link it up, then you can go back to canary. Something something oauth security something, I dunno.
