### ISSUE TITLE
Typing notifications cause high CPU usage when focused.

### ISSUE THREAD

**Issue by fauxm** [crmarsh/discord-linux-bugs#191]
I noticed my laptop's battery life was taking a hit occasionally when using Discord and wanted to know why.

I checked the CPU usage, and have correlated higher CPU usage with the "Nickname is typing..." message. The `Discord --type=renderer` process has the most usage, ranging from ~45% to over 100%, followed by the `--type=gpu-process` process, followed by the parent process (just `Discord`, not the zygote).

The problem occurs when the message appears, and disappears when the message disappears, so I'm relatively certain that this is the cause of the issue. It also only happens when Discord is focused. If it isn't (even if it's on screen and visible), CPU usage is normal.

If it's of any relevance, I'm launching Discord with the `--force-device-scale-factor=1.5` launch option (for high-dpi support) and with a nice level of +10. This is on Linux 4.9.0-gentoo, and the graphics driver is xf86-video-intel. No desktop environment or compositor (i3wm).

**Comment by ammarx** [comment]
Having the same issue here as well.. any luck fixing this?

**Comment by crmarsh** [comment]
This is kinda unfortunate, but I'm not sure it is worth the effort to try to fix. This is just a consequence of any kind of animation being CPU intensive in Electron; we've already made it so that the animation only plays if the Discord window is focused.
