### ISSUE TITLE
Icon Blurry in Systray?

### ISSUE THREAD

**Issue by Hacksaurus** [crmarsh/discord-linux-bugs#192]
This issue may just be something with my icons, but just wanted to make sure, because my icon in Ubuntu isn't blurry at all... I am using Arch on XFCE.

This is what it looks like.
![screenshot_2017-02-13_20-02-34](https://cloud.githubusercontent.com/assets/24832107/22914774/5f29e468-f227-11e6-94c2-9de38ec2267e.png)

Is this a problem with Discord or my icons?
Thanks for any help!

**Comment by OvermindDL1** [comment]
I think it is just because it is not an svg icon, but I think there was another issue about this too?

**Comment by skwerlman** [comment]
There was: #172

**Comment by Hacksaurus** [comment]
Ok I'll check that thread! Closing this one!
