### ISSUE TITLE
Font color in light/white theme is too light.

### ISSUE THREAD

**Issue by raphendyr** [crmarsh/discord-linux-bugs#194]
Font color on white theme is unreadable. It should be black.

![screenshot_20170221_000644](https://cloud.githubusercontent.com/assets/2327687/23143356/a6467f30-f7c9-11e6-8180-5943d8b23f1f.png)

**Comment by crmarsh** [comment]
I dunno if I agree, but then I'm not much of a UI designer. This is not a Linux specific bug, though, this is more what our [feedback site](https://feedback.discordapp.com) is for.
