### ISSUE TITLE
Closing Discord window leaves hidden process

### ISSUE THREAD

**Issue by achurch** [crmarsh/discord-linux-bugs#197]
If I close the Discord window, the DiscordCanary process keeps running despite having no windows open. I can reopen the window by running DiscordCanary again, but I have no way to terminate the process except kill -9, which probably doesn't do nice things to persistent state -- even SIGTERM doesn't seem to work, I assume because it's caught.

If the intent is for the process to persist across window close and reopen, there probably needs to be an explicit "quit" menu option somewhere. (Or is there one and I'm just overlooking it?)

**Comment by SirDoctors** [comment]
There's a quit button in the notification bar, just right click the icon. I do agree though that there should be an alternative place for that. (so people who don't have a notification bar can still close discord correctly)

**Comment by achurch** [comment]
I don't have a notification bar.

**Comment by dpeukert** [comment]
You can use Ctrl+Q.

**Comment by achurch** [comment]
That works fine, thanks. (Might be worth documenting somewhere?)
