### ISSUE TITLE
llvm/clang libc++

### ISSUE THREAD

**Issue by Thaodan** [crmarsh/discord-linux-bugs#201]
Currently discord-canary links to clangs libc++ will this also be for the stable version and why?

**Comment by skwerlman** [comment]
This is probably for similar reasons as why libcups is also linked; discord is built using electron, which is basically chrome.

**Comment by Thaodan** [comment]
That's maybe true.
But chromium doesn't need clang and can just use gccs libstdc++.

**Comment by crmarsh** [comment]
This will also be for the next stable version. It is our dep, not forced by electron, afaik. Why? It is better and we use some stuff that it has which libstdc++ lacks.

**Comment by Thaodan** [comment]
And thats what?  Wich gcc Version was used before?
