### ISSUE TITLE
Javascript error in main process 

### ISSUE THREAD

**Issue by Deathkiller1010** [crmarsh/discord-linux-bugs#206]
I keep getting this error when I start discord help please
![error 3_05_2017 9_31_23 am](https://cloud.githubusercontent.com/assets/20531089/25643570/df798368-2fe3-11e7-98e0-2f083739dd69.png)

**Comment by crmarsh** [comment]
Looks like an error on Windows? I'm not really sure what the error is exactly (that helpful error dialog cuts off the important part of the stack trace), but my guess is some json file got corrupted, maybe try deleting all of `%appdata%\discord\*.json`
