### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by Svetomech** [crmarsh/discord-linux-bugs#209]
What the title suggests. Is there going to be a [Flatpak](http://flatpak.org/hello-world.html) version of Discord client?

**Comment by fishxz** [comment]
it seems like there is a flatpak version on http://flatpak.org/apps.html now.

**Comment by Svetomech** [comment]
Doesn't seem like it's an official one, but I guess it'll do. I'm just unsure of the way it's going to update - through the usual `flatpak update` command or through the app's self-update feature. I think these methods are gonna conflict unless the latter is disabled in the flatpak version.
