### ISSUE TITLE
New emoji system prevent quick emojis

### ISSUE THREAD

**Issue by Uriei** [crmarsh/discord-linux-bugs#211]
Simply enough, when I want to just type :D on discord, it replaces it with :regional_indicator_d: , I know that adding a space afterwards prevents that, but sometimes you only want to send a quick classic emoji, my suggestion, change the default behavior of Enter to select the emoji from the list to TAB or something like that ;)
![image](https://user-images.githubusercontent.com/6078221/27988264-2859b3a0-641e-11e7-8888-83e963b1620b.png)

**Comment by Uriei** [comment]
Whatever, I've just found you have a server for this, you should really improve the documentation about bug reporting and Canary versions.

**Comment by crmarsh** [comment]
Yeah, we know about this one :-/

Which documentation would you like to see improved?
