### ISSUE TITLE
Text From Previous Message Included When Uploading Image

### ISSUE THREAD

**Issue by StewieFellows** [crmarsh/discord-linux-bugs#212]
UPDATE: I thought it was happening with insta-upload, but it's actually when using the file upload button.

Since the latest update recently, I'm noticing that if I send a message with just text, then upload an image using the + button, the message will contain the text of the message I previously posted. The workaround is to clear out the text box and modify it with the desired message before posting.

**Comment by skwerlman** [comment]
this is not linux-only; i'm also seeing it on my windows box

**Comment by crmarsh** [comment]
I'm gonna close this here since it is not really Linux specific; it is a bug and it's on our todo list, though.

**Comment by StewieFellows** [comment]
Thank you!
