### ISSUE TITLE
Update check disabling

### ISSUE THREAD

**Issue by dangranos** [crmarsh/discord-linux-bugs#214]
So, apparently DiscordCanary refuses to launch if the version is even slightly outdated. That, uh, seems to have been introduced only in version 19, because every single time before that it was just starting up normally, with a small icon "Host (or was it native?) update required".

What I want to say, there should be NO check for outdate-ness of the version, at least not in a way that prohibits downgrading or using older versions, *especially* since version 20 seems to refuse to start up (See #213)

**Comment by SapphireTactician** [comment]
Well, it IS Canary, so checking for the latest stuff is kind of the point, but it should allow you to rollback by at least one version in the event it breaks.

**Comment by KeiroD** [comment]
The fact that it is Canary doesn't excuse not having an ability to roll back to the last known working state of Discord.

**Comment by SapphireTactician** [comment]
Perhaps, but from having done QA work myself, I get why they did it as it's pretty annoying to see people filing bugs against outdated builds. Best case scenario, the team realizes it's from an old build and scolds the tester to upgrade, worst case scenario - everyone wastes time and money on a wild goose chase for a bug that was already addressed or no longer relevant.

**Comment by dangranos** [comment]
@SapphireTactician Or they just require a mandary "What's your version?" answer. And just throw a template "What's the version?" question if there's no such answer in the issue.

Disabling any kind of rollback, that you would mostly use only in case of sudden breaking bugs, is just as annoying for users as having to deal with fixed bugs for developers. The best variant is to show a ***huge*** warning about how outdated your version is and so on every startup and asking "Do not report any bugs if you did not update. Do you understand?". Or even simplier, just ask that in the terminal, avoiding GUI work. And yes, that would break auto-startup scripts and etc, but that's the point, canary should be used manually by person, to be looked over all the time and so on.

**Comment by StewieFellows** [comment]
Completely agree. It makes no sense to force a user to upgrade their software when it literally makes the program un-usable. Granted the developers obviously didn't know this was going to happen with 0.0.20, but this risk will continue to exist with every release. Because of this, a user should at least be able to roll back a single version for when events like this happen. I don't believe allowing that would create a significant amount of unneccesary bug reports.

**Comment by Siilwyn** [comment]
An option to still launch the app if there is an update available would be good. I'm currently in the train on a slow internet connection unable to download the new version.

**Comment by crmarsh** [comment]
You make fine points, I don't see the benefit to putting work into this right now.
