### ISSUE TITLE
Links won't open

### ISSUE THREAD

**Issue by mphe** [crmarsh/discord-linux-bugs#215]
When i try to open links in Discord, a xdg-open process and a firefox process with the correct URL will spawn. But for some reason the window/tab won't open, instead another firefox process appears that is marked as \<defunct>.

I checked my xdg configs, everything is set correctly and works in every other application.

For example, this is the output that ps shows me, when I try to open a link to "www.google.de":
```
marvin   19426  0.0  0.0  15648  3556 ?        S    17:05   0:00 /bin/sh /usr/bin/xdg-open https://www.google.de/
marvin   19488  0.2  0.5 382828 42828 ?        Sl   17:05   0:00 /usr/lib/firefox/firefox https://www.google.de/
marvin   19490  0.0  0.0      0     0 ?        Z    17:05   0:00 [firefox] <defunct>
```

My system:
Arch (kernel 4.11.9-1)
Discord Canary 0.0.22
Awesome WM (also tested on Mate, but same behaviour)

**Comment by OvermindDL1** [comment]
What happens if you xdg-open a url at your terminal?

**Comment by mphe** [comment]
Works as expected.

**Comment by OvermindDL1** [comment]
Is your Discord running in any kind of sandbox or container or on the main host and in the same profile as your firefox is running?

**Comment by mphe** [comment]
Running on the main host.
Shouldn't it pick the current/default profile automatically?

**Comment by OvermindDL1** [comment]
> Shouldn't it pick the current/default profile automatically?

By profile I mean the same `$DISPLAY` (and not over another X server or so).

If all the same, then unsure, it works on my system (though I'm using chrome as the primary browser), may have to wait for someone else to test that has Firefox set as their primary browser.

**Comment by mphe** [comment]
Yes, it's running on the same profile.
Thanks for trying to help though.

**Comment by crmarsh** [comment]
It doesn't [look like](https://github.com/electron/electron/blob/master/atom/common/platform_util_linux.cc#L59) electron is doing anything too crazy here. They set `MM_NOTTTY=1`, not sure if that matters.

**Comment by mphe** [comment]
I just tried running xdg manually  with `MM_NOTTY=1` but it still works, so this doesn't seem to matter.
Also, it doesn't seem to be an electron bug, because I can open links from other electron apps without problems.

**Comment by mphe** [comment]
Seems to be fixed now.
Not sure though if it was the recent Discord or Firefox (55) update.
