### ISSUE TITLE
Screen sharing crashes Discord

### ISSUE THREAD

**Issue by zatherz** [crmarsh/discord-linux-bugs#219]
When you press the screen share button while in a call, a window appeard that lets you choose whether you want to share the whole screen or a program. No matter which option you choose, the moment you press the button to confirm, Discord is gonna freeze and then restart after a few seconds.

This is the only thing that appears in the log after trying to start the screen share:
```
Report Id: OK
[WebContents] crashed... reloading
```

Screen sharing works flawlessly on Windows.

**Comment by half-cambodian-hacker-man** [comment]
+1 - Occurring for me as well.

**Comment by advaith1** [comment]
Reported here: https://trello.com/c/V3dwAiXx/30-discord-crashes-upon-trying-to-share-screens. Report number: 3080

If you can reproduce, please join the [Discord Testers server](https://discord.gg/discord-testers) and use the !canrepro command on it.

**Comment by Stolous** [comment]
Same issue here, tried with NVidia drivers and only with integrated intel.
kernel x86_64 Linux 4.12.8-2-ARCH

**Comment by MaCroX95** [comment]
I can confirm the bug, happens every time when I try to share the screen!

Distro: Ubuntu 16.04
Desktop: Plasma 5.10.5
Kernel: x86_64 Linux 4.10.0-32-generic
GPU driver: Tried on both Nvidia proprietary drivers and intel open-source driver, occurs on both
Terminal output when error happens:
![image](https://user-images.githubusercontent.com/21268648/29775169-5b069a80-8c04-11e7-9daa-d5d4ad56b1b5.png)

**Comment by theo546** [comment]
crash too on Archlinux, GNOME 3, on kernel 4.12.8-2.

**Comment by Admicos** [comment]
I have a workaround over [here](https://redd.it/6x1q6b).

**Comment by half-cambodian-hacker-man** [comment]
@Admicos: Also works as a workaround for #220.

**Comment by theo546** [comment]
Up

**Comment by Jerem584** [comment]
error when launching the script 

[x11grab @ 0x559bc32c3640] Capture area 1920x1080 at position 0.0 outside the screen size 1280x1024

**Comment by Admicos** [comment]
@Jerem584: Edit the script and replace 1920x1080 with your monitor resolution.

**Comment by ogkloo** [comment]
Same happens to me on xubuntu 16.04, running i3, compton.

**Comment by DougTy** [comment]
Still happening on the latest stable update for me
Arch + compton + xfce + proprietary nvidia

**Comment by JShorthouse** [comment]
Same issue, trying to screenshare makes discord restart.

Debian Stretch + i3wm + Compton+ Radeon driver

**Comment by andyczerwonka** [comment]
Same here. Attempt at screen share crashes and restarts Discord.

`Linux groot 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Nimbleguy** [comment]
Same as well. Gentoo + compton + i3wm + Intel integrated graphics.

**Comment by SergioRosello** [comment]
Same issue :( 
manjaro (arch linux) + gnome

**Comment by Frigerius** [comment]
Windows crashes as well.

**Comment by crmarsh** [comment]
This is fixed in canary now.

**Comment by phelipe** [comment]
Same issue 
manjaro (arch linux)

**Comment by sl4w3k** [comment]
Same issue on Linux Mint 18.2

**Comment by advaith1** [comment]
@sl4w3k @phelipe are you guys using canary?

**Comment by phelipe** [comment]
@advaith1 you were right, I was using another version. It was necessary to install another by AUR. Thank you!

**Comment by sl4w3k** [comment]
cannary works well :)

**Comment by qptain-Nemo** [comment]
In Canary sharing of the entire screen works but trying to select a window still crashes for me on Arch.

**Comment by kamek-pf** [comment]
canary crashed right off the bat for me and a co worker ("Well this is awkward").
Using Arch, installed from the AUR (discord-canary)

**Comment by MaCroX95** [comment]
I can confirm the issue on Linux Mint and Nvidia GTX 970 proprietary drivers.

**Comment by nicodonof** [comment]
Same here !

**Comment by Serkan-devel** [comment]
Same on the stable appimage version.

**Comment by Stanleydevv** [comment]
Same problem. Really annoying.
