### ISSUE TITLE
Unable to install without manually installing libappindicator1/libindicator7 on fresh Ubuntu install

### ISSUE THREAD

**Issue by RPiAwesomeness** [crmarsh/discord-linux-bugs#23]
From what I can tell, Discord Canary depends on libappindicator and libindicator7, which aren't installed by default on Ubuntu 16.04 (and older versions too I believe).

I don't have any experience in creating DEBs, but if you could make those two be installed as needed, that would make it easier to install!

Here's the full `dpkg` error:

```
$ sudo dpkg -i Downloads/discord-canary-0.0.5.deb 
Selecting previously unselected package discord-canary.
(Reading database ... 182610 files and directories currently installed.)
Preparing to unpack .../discord-canary-0.0.5.deb ...
Unpacking discord-canary (0.0.5) ...
dpkg: dependency problems prevent configuration of discord-canary:
 discord-canary depends on libappindicator1; however:
  Package libappindicator1 is not installed.

dpkg: error processing package discord-canary (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu3) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160415-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 discord-canary
```

**Comment by X-m7** [comment]
@RPiAwesomeness Run sudo apt-get install -f, it will fix the dependency issues and configure discord as well.

**Comment by AidanT** [comment]
I had the same issue on a fresh install of 16.04 LTS but not 14.04 LTS. Like @X-m7 said sudo apt-get install -f fixed it.

**Comment by X-m7** [comment]
I think using GDebi or another graphical installer might help, if I remember correctly GDebi will install the dependencies automatically along with the deb file.

**Comment by RPiAwesomeness** [comment]
@X-m7 @AidanT That's what I ended up doing, but it's still an issue that should be looked into.

**Comment by abobier** [comment]
I think it's not an issue because `sudo dpkg -i *.deb` doesn't install dependencies.
You need to use this command to force install dependencies `sudo dpkg -i --force-depends *.deb`

**Comment by AidanT** [comment]
@abobier Even when using sudo dpkg -i --force-depends *.deb it would still require sudo apt-get install -f

**Comment by abobier** [comment]
@AidanT That's true.

**Comment by X-m7** [comment]
Another way to deal with the issue would be to package it in one executable which would then install the app and its dependencies (the way VMWare Player and Genymotion for Linux are packaged). It might even help with making the app distribution-independent. That said I think the current method works just fine.

**Comment by RPiAwesomeness** [comment]
@abobier Ah, I did not know that. I guess this isn't an issue after all.

@X-m7 I would agree having a .sh installer would be useful

**Comment by crmarsh** [comment]
To actually fix this bug I'd need to write a patch for dpkg; not out of the question, but doesn't really feel like it is in scope for this project.

For now I think distributing a deb with a dependency list suffices. I keep hearing I should make a PPA. Anyway, once this hits stable I'll revisit packaging.
