### ISSUE TITLE
Restart loop when I enter the voice channel

### ISSUE THREAD

**Issue by Davinais** [crmarsh/discord-linux-bugs#235]
After updating Discord 0.0.27, when I entering the voice channel, the main window just closed and restarted. After the loading process completed, it shutdowns again and restarts again endlessly unless you kill it manually.

0.0.24 works perfectly, I don't sure if 0.0.25 is worked well.
I'm using Linux kernel 3.13.0.37 in Mint 17 64-bit

Here's the output of terminal.

> DiscordCanary 0.0.27
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/david/.config/discordcanary/0.0.27/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
/usr/share/discord-canary/DiscordCanary --type=renderer --no-sandbox --primordial-pipe-token=29EEC66102E770BB3026A1C4440D221C --lang=zh-TW --app-path=/usr/share/discord-canary/resources/app.asar --node-integration=true --webview-tag=true --no-sandbox --background-color=#282b30 --enable-blink-features=EnumerateDevices,AudioOutputDevices --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --disable-gpu-compositing --service-request-channel-token=29EEC66102E770BB3026A1C4440D221C --renderer-client-id=6 --shared-files=v8_natives_data:100,v8_snapshot_data:101: symbol lookup error: /home/david/.config/discordcanary/0.0.27/modules/discord_voice/discord_voice.node: undefined symbol: __atomic_load
[WebContents] crashed... reloading
Feature redeclared; is this a duplicate flag?  voice_sound_stop_loop
Feature redeclared; is this a duplicate flag?  voice_relative_sounds
Feature redeclared; is this a duplicate flag?  voice_panning
Feature redeclared; is this a duplicate flag?  voice_multiple_connections
Feature redeclared; is this a duplicate flag?  media_devices
Feature redeclared; is this a duplicate flag?  media_video

I think the problem is 
`symbol lookup error: ~/.config/discordcanary/0.0.27/modules/discord_voice/discord_voice.node: undefined symbol: __atomic_load`. 
Any solutions about that?

**Comment by sfirfi** [comment]
There currently is no solution for that, but its a reported bug and its marked with a high priority so it should be fixed soon. 
Link to the report for more infos: https://trello.com/c/Dsu76DKP

**Comment by crmarsh** [comment]
This is fixed now
