### ISSUE TITLE
Middle click opens links in a hidden, inaccessible new tab

### ISSUE THREAD

**Issue by tjb0607** [crmarsh/discord-linux-bugs#237]
This is most noticable if you middle click a video link, which will end up playing in the background until you restart the Discord client entirely. I usually middle click image uploads to open them in browser on my main display in one click, but now that functionality is broken.

Tested on Discord Canary v0.0.29 on Arch Linux

**Comment by RDardelet** [comment]
Can reproduce.

*Discord Canary v0.0.29, Ubuntu 16.04 Unity*

**Comment by Narthorn** [comment]
Can reproduce with Canary v0.0.29 on Arch as well!

**Comment by lust3088** [comment]
Can reproduce too. As said above, it opens the video in the background - the only way of forcing the video to stop is to close Discord and reopen.

*Discord Canary v0.0.29 on Arch Linux*

**Comment by tjb0607** [comment]
Tested again with Discord Canary v0.0.31 on Arch Linux, issue seems to have been resolved.
