### ISSUE TITLE
Voice chat stops working after changing wifi networks

### ISSUE THREAD

**Issue by MingweiSamuel** [crmarsh/discord-linux-bugs#28]
If I am connected to a voice channel, then change wifi networks, voice chat stops working. It shows my icon as being the the voice channel, but it's not actually connected (can't hear or broadcast), and clicking the "disconnect" button does nothing.

I'm currently on ubuntu 16.04 LTS, but I noticed the problem on the previous version of Ubuntu as well.

**Comment by MingweiSamuel** [comment]
also, re-opening the app does nothing to fix the problem, so the app seems to be softlocked until rebooting my computer.

**Comment by SwooshyCueb** [comment]
Are you still experiencing this issue? I haven't run into any trouble with network changes

**Comment by MingweiSamuel** [comment]
I haven't tried since then

**Comment by crmarsh** [comment]
This should be fixed as of 0.0.10
