### ISSUE TITLE
Msg's only get sent after suspend, not received

### ISSUE THREAD

**Issue by greenbigfrog** [crmarsh/discord-linux-bugs#29]
After I wake my PC up again after suspending it, it won't show new msg's but will still send msg's... So it kind of only works one way...

Steps to reproduce:
1. Suspend your PC
2. wake it up again
3. send a bot command f.e.
4. you won't get a respond
4. reload discord
5. after this you will see that the bot has responded actually

**Comment by Sejsel** [comment]
I can confirm this happens to me too. You also do not get the messages which were sent when the computer was suspended.

**Comment by TheDoctorsLife** [comment]
This should be any easy fix if there's a way for electron to tell that the computer has woken up from suspension, then just reloading discord if that is true.

Also I can't reproduce this locally by either hibernating or suspending. How are you suspending @green-big-frog & @Sejsel?

**Comment by crmarsh** [comment]
I could just reload, yeah, but it sounds like the server folks have a better fix in the works, so I'll wait on that. FWIW, OSX has this same bug :-/

**Comment by green-big-frog** [comment]
@TheDoctorsLife just suspending normally on Ubuntu 16.04 (has existed also with lower ubuntu versions)

**Comment by greenbigfrog** [comment]
In the mean time I switched to arch. After using `systemctl suspend` (systemd suspend) it automatically reloads(?).

Not sure if it still exists for other systems...

**Comment by crmarsh** [comment]
This was deployed a bit ago, and in my quick test seems to be working. LMK if it is still broken for you.
