### ISSUE TITLE
Crash after entering big servers

### ISSUE THREAD

**Issue by CPyJIb** [crmarsh/discord-linux-bugs#3]
Have a strange bug, when I enter big server, client just crash and reload. Same bug on unofficial discord wrapper, black screen after entering. Works fine on browsers, Arch Linux + Plasma.

**Comment by crmarsh** [comment]
I'm probably going to need more info to track this down. I'm in several of the largest servers and it does not crash for me.

**Comment by snipeytje** [comment]
a black screen on some servers sounds like it might be related to [this](https://github.com/XNBlank/discord-linux/issues/26) from the unofficial wrapper

**Comment by crmarsh** [comment]
Perhaps. I was hoping that a [fix from electron](https://github.com/electron/electron/releases/tag/v0.36.9) would fix those font problems.

**Comment by CPyJIb** [comment]
I had freetype2-infinality but it does not fix the problem. Gonna test it after I can launch it :D

**Comment by CPyJIb** [comment]
freetype2-ubuntu fix it for me

**Comment by CPyJIb** [comment]
well, freetype2 works too, seems electron fix works fine

**Comment by crmarsh** [comment]
Okay, I'm going to close this since I guess it is not crashing for you now.
