### ISSUE TITLE
Open Windows Or Proccess

### ISSUE THREAD

**Issue by c42759** [crmarsh/discord-linux-bugs#30]
Right now I have League Of Legends running on Playonelinux, and I use a virtual desktop to limit the used area.
That window has the name "Default - Wine Desktop", but on systemon monitor it's possible to see the LolClient.exe running.

In some way, discord should be loocking for running aplications, and not open windows I gues

**Comment by crmarsh** [comment]
I gather everything in the process list (reading /proc) that belongs to your user; I am only scanning the window list to get a better guess of the name. A few things are excluded by default: `/bin`, and `*/sbin/*` just to try to cut down on the non-game junk.
