### ISSUE TITLE
Unable to access right click menus on Arch/xfce

### ISSUE THREAD

**Issue by rybro** [crmarsh/discord-linux-bugs#32]
Anytime I try and right click to highlight or to paste text, I get no menu. This happens in a different nw.js application so I'm not sure if it's specific to that (not sure if this is built in that).

**Comment by ahjolinna** [comment]
I have this same issue with ChakraOS (KDE/plasma5)

**Comment by dpeukert** [comment]
@rybro Discord is built on Electron.

**Comment by rybro** [comment]
@dpeukert i'm aware, however, i've only ever encountered this issue in another application, a web.skype port with nw.js and then this linux canary build. i don't have the issue with atom, which is electron.

**Comment by crmarsh** [comment]
Is this still a problem in the newer version?

**Comment by rybro** [comment]
yep, all fixed for me now. same setup. arch/xfce

thanks :+1:
