### ISSUE TITLE
Input box scrolling

### ISSUE THREAD

**Issue by Sejsel** [crmarsh/discord-linux-bugs#34]
This is more of a request than a bug report.

The text input box does not support scrolling using a mouse. It would be nice if one could use the scroll wheel to scroll through text when typing text which spans many lines.

Right now, the only way is to move the cursor using a keyboard and scroll in a very inefficient manner.

This does not work in the browser version of discord either.

**Comment by crmarsh** [comment]
This is not really specific to the Linux version, or even the native client (as you mention), so I'm gonna close it here, but we do have a ticket for this on our regular bug tracker.
