### ISSUE TITLE
Discord transmits sound without plugged in microphone

### ISSUE THREAD

**Issue by madoar** [crmarsh/discord-linux-bugs#37]
Hi all,
I observe the effect, that my discord client transmits sound even without a plugged in microphone.
This happens, when I have plugged in speakers and I'm playing some music with bass a little louder.
I can observe then, that some sound spikes are transmitted on discord.
This was also confirmed by a few friends of mine, who asked what I'm listening to, where I discovered, that at this time I hadn't a microphone plugged in.

I observed this behaviour with version 0.0.7 and 0.0.8.

Greetings
Marc

**Comment by crmarsh** [comment]
That sounds like magic to me, perhaps your computer has a built in mic you were unaware of?

**Comment by Jibodeah** [comment]
This is most likely just a quirk of Pulseaudio. Namely if your microphone isn't plugged in it'll fail back to another input stream, in this case the monitor of your audio output, which is always there. You'll most likely get the same problem in pretty much anything that records audio on a system using Pulseaudio.

**Comment by crmarsh** [comment]
I'm gonna call this one Pulseaudio's bug

**Comment by madoar** [comment]
Hi,
sorry for the late answer from me.
I took a look at my settings and did a few tests and it seems you're 
right it seems to be because of my configuration.
When I record my audio input with the tool `arecord` when I have no 
microphone plugged in, I get my output with a little noise in the 
background.

Greetings
Marc

Am 20.05.2016 um 18:21 schrieb Chris Marsh:
