### ISSUE TITLE
System tray icon missing

### ISSUE THREAD

**Issue by crmarsh** [crmarsh/discord-linux-bugs#4]
Elementary OS

**Comment by BillyGalbreath** [comment]
Can confirm for Gnome 3 on Debian Jessie (Works fine on Debian Sid, though)

**Comment by crmarsh** [comment]
Try 0.0.3, lmk

**Comment by Daverball** [comment]
The tray icon goes missing for me on 0.0.3 as well, the first start of the app in a session usually brings up the tray icon, but after closing discord any subsequent starts of the application won't show a tray icon.

**Comment by crmarsh** [comment]
Oh, simply never close Discord then :-p

Okay, I'll try that out, thanks.

**Comment by X-m7** [comment]
Just to clarify, is the issue about the tray icon being invisible or about it not being present at all? On my laptop (Debian 8, v0.0.4) it's the former.

**Comment by GreyAsteroid** [comment]
Was able to fix this issue by setting the environment to Unity while executing like so
`env XDG_CURRENT_DESKTOP=Unity /usr/share/discord-canary/DiscordCanary`

Seems to be a problem with Pantheon not being treated correctly like Unity is.

**Comment by GreyAsteroid** [comment]
It seems like the newest version of elementary OS no longer supports ayatana indicators. There's a new API for Wingpanel indicators though. 

Here's the code for a Wingpanel indicator using the new API, [wingpanel-indicator-session](http://bazaar.launchpad.net/~wingpanel-devs/wingpanel-indicator-session/trunk/view/head:/src/Indicator.vala)

**Comment by GreyAsteroid** [comment]
This seems to be a known issue with electron not understanding that Pantheon is working appindicator environment. 

The bug can be tracked here https://github.com/electron/electron/issues/5050

**Comment by GreyAsteroid** [comment]
This issue has been fixed by a recently merged PR in electron https://github.com/electron/electron/pull/7319

**Comment by crmarsh** [comment]
Oh, nice :+1:

**Comment by GreyAsteroid** [comment]
electron 1.4.2 has been released ( https://github.com/electron/electron/releases/tag/v1.4.2 ) containing the new elementary tray icon fix.

**Comment by crmarsh** [comment]
I'm not looking forward to all the other bugs we'll pull in, but sounds like it's time to upgrade :-)

**Comment by GreyAsteroid** [comment]
Issue still present on release 0.0.9

**Comment by crmarsh** [comment]
Yeah, I have not upgraded to 1.4.2 yet, we're still on 1.3.3.

**Comment by skwerlman** [comment]
New electron coming in 0.0.10?

**Comment by giuliandenicola** [comment]
Is there a way to manually update the electron?
`env XDG_CURRENT_DESKTOP=Unity ` is not working anymore for my after a clean install.

**Comment by crmarsh** [comment]
Yeah, 0.0.10 is (will be?) using electron 1.4.4. I'll ship it pretty soon.
