### ISSUE TITLE
Gnome file chooser not showing image previews. 

### ISSUE THREAD

**Issue by ideceddy** [crmarsh/discord-linux-bugs#42]
I'm not really sure if this is a bug or intentional on your part but ill post this here anyway. when uploading files through discord Gnome's file choosers dialog box doesn't show previews or thumbnails for images I was reading online and it turns out that this is something that needs to be turned on buy the devs. It would be really nice to be able to see what image I'm uploading before i upload it. thanks :)

the post I read: 
"The image preview is an optional feature of the Gnome's file chooser dialog. It has to be enabled on a per-program basis (meaning that to use it in Firefox, Firefox developers have to enable it). This is because not every application has any need for picture previes (think about text editors, for instance).
You should send feedback to Firefox developers and ask them to enable the picture preview."

**Comment by X-m7** [comment]
By image previews you mean the big thumbnails right? Here I see it as a list, but the previews are there in the form of small icons. Debian 8, GNOME 3.14.

**Comment by ideceddy** [comment]
Yes the big thumbnails to the right of the screen. I have small thumbs as icons on the images but its to small to tell what the image is. Debian 8, Openbox.

**Comment by ahjolinna** [comment]
it would be nice if you could use more "native" file chooser dialog in Discord instead of this current **** ...or at least choose between nautilus (gnome +spinoffs) and Dolphin (kde) and the current one that is now in use could be a "fallback"

**Comment by crmarsh** [comment]
We just use the electron file dialog [API](https://github.com/electron/electron/blob/master/docs/api/dialog.md). It does not appear to have options available for that at the moment.

**Comment by stoatally** [comment]
It is because electron is using the Gtk2 file dialog and not the Gtk3 dialog.

**Comment by ahjolinna** [comment]
I found in [arch wiki](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#KDE_file_dialogs_for_GTK.2B_applications) an old'ish hack/workaround called [Kgtk](https://www.linux-apps.com/p/1081260) for KDE that forces gtk apps to use KDE file dialogs, I tried to use it on discord-canary but didnt work directly, but with app called [franz](http://meetfranz.com/) (that has discord and is electron based) it somewhat worked...aka it launched both file dialogs -_- 

anyway it would be nice if something like this could be support but needs to be enabled separately

PS. you need to add discord/franz app names to the kgtk script for it to (somewhat) work (recognize them)

**Comment by Milaine** [comment]
This issue is still relevant and very annoying, did you make any progress on it yet?
 Kubuntu 17.04

**Comment by ahjolinna** [comment]
I think this would be possible as Discord is based on Electron tech and its based on chromium (and other stuff) ...and on chromium it uses the native KDdialog on KDE.

maybe it has something to do with that electron is still dependent on gtk2

I personally I really don't care anymore as all these webapps suck ass and always will...It's just a half baked solution to get cross platform support or just linux version...sigh
I'm not even sure that I would say that this is better than nothing

**Comment by ahjolinna** [comment]
I know this is little bit of topic, but ...I just have to ....
more reason why the whole webapp sucks ass and why discord should be using qml/qt instead:
![image](https://user-images.githubusercontent.com/6993072/28884512-d372ae18-77ba-11e7-8b4d-448ff9add7c2.png)

Sequality software engineering compared Qt with HTML5 in terms of openness, UX, costs, and much more. Learn more from their white paper and infographic on their blog: http://hubs.ly/H08cVVF0

**Comment by crmarsh** [comment]
If electron upgrades, we'll get this when they do. No, I'm not going to rewrite everything from scratch in Qt or anything else (at least in the near term).
