### ISSUE TITLE
Random App Crash

### ISSUE THREAD

**Issue by AKPWebDesign** [crmarsh/discord-linux-bugs#43]
Sorry, didn't really know what to title this issue. I just had discord-canary 0.0.8 running in the background (not doing much of anything besides sitting in a text chat while I worked in another window), and it crashed. Here's a [link to the Ubuntu .crash file](https://drive.google.com/file/d/0B5wWwqnenRLpYjZFaWlRamJUWVk/view?usp=sharing), in case it can be of any use, and I've got a table of some of the more relevant information from the crash file below. I couldn't find any sort of log file from Discord, and so far, I'm unable to reproduce the issue.

| Name | Value |
| ------------- | ------------- |
| Discord Version  | 0.0.8  |
| Ubuntu Version  | 15.10  |
| Architecture | amd64 |
| Top of Stacktrace | v8::base::OS::Abort() from discord-canary/libnode.so |
| Title of crash | DiscordCanary crashed with SIGILL in v8::base::OS::Abort() |

Hopefully I've provided enough information... if not, let me know, and I'll try to gather more.

**Comment by crmarsh** [comment]
Looks like a crash in Node's garbage collector :-/
There's probably not anything I can do about this one, except pulling in newer versions of Node where this is fixed.

**Comment by crmarsh** [comment]
Oh, I should point out, I get crash report data automatically, so gathering these kinds kinds of crash dumps is not required.

**Comment by AKPWebDesign** [comment]
Oh, cool. I figured you got some info, but wasn't sure exactly what is able to be collected automatically.

**Comment by crmarsh** [comment]
Thank you for your help and the bug report, btw, didn't mean to sound dismissive :-)

There is probably more useful info in what you sent, but mostly what I look at are the callstacks anyway.

**Comment by AKPWebDesign** [comment]
No worries! I totally get it.
