### ISSUE TITLE
Debugging Speech chat freezes and it closes on Kubuntu 16.04

### ISSUE THREAD

**Issue by Serkan-devel** [crmarsh/discord-linux-bugs#47]
When I click the Debugging option at speech chat it opens a new window, freezes then closes discordapp by itself.

**Comment by Leseratte10** [comment]
Happens for me too, on Ubuntu 15.10 with Discord. Any debug logs we could give you to fix this?

**Comment by Leseratte10** [comment]
(Seems to be a duplicate of #12 )

**Comment by Serkan-devel** [comment]
where do I find the logs?

**Comment by crmarsh** [comment]
Yeah, this is the same as #12. I have a guess about what the bug is, I'll try to get a fix for it soon.
