### ISSUE TITLE
Support for ARM CPUs

### ISSUE THREAD

**Issue by Serkan-devel** [crmarsh/discord-linux-bugs#48]
It would be great to run Discord on a Raspberry Pi while playing Robot unicorn attack revolution on a browser. Or run it there as a docker container (I'm working on that for x86). The problem with teamspeak is it doesn't support ARM neither Client nor Server.

**Comment by crmarsh** [comment]
I have not tried compiling for ARM, but I suspect it is possible. I'm not sure it is really desirable, though, since at 1GB of RAM in the Pi, Discord would be using a pretty significant fraction. It seems like a funny thing to try out, but I dunno how useful it would actually be to anyone.
