### ISSUE TITLE
Code block width/scrollbar Issues

### ISSUE THREAD

**Issue by ccubed** [crmarsh/discord-linux-bugs#5]
Platform: Arch 64bit
Client: Discord Canary 0.0.2 from AUR
Issue: When codeblocks are inserted and a scrollbar is put in the chat window, that scrollbar rolls off the edge and will not scroll. It also takes away my avatar.

![ArchScroll](http://i.imgur.com/Mk60kbB.png)

**Comment by crmarsh** [comment]
This impacts all platforms, and is in browser, side effect of upgrade to Chrome 49 I think.

**Comment by ccubed** [comment]
I do indeed have Chrome 49.

**Comment by TheSisb** [comment]
willfix

**Comment by ccubed** [comment]
Just letting you know that on Arch I just got Chrome 50 and the problem persists.

**Comment by sudopluto** [comment]
@ccubed Discord is probably using CEF to make the desktop app. It is completely independent from the chrome browser that you have installed and is used to make desktop apps with web technology.

**Comment by crmarsh** [comment]
We use [Electron](https://github.com/electron/electron), which is currently tracking Chrome 49.

**Comment by crmarsh** [comment]
I think this was fixed.
