### ISSUE TITLE
Discord crashes when PulseAudio restarts

### ISSUE THREAD

**Issue by ThePooN** [crmarsh/discord-linux-bugs#50]
Discord doesn't crash when PA is killed, but it crashes when it spawns again.

**Comment by crmarsh** [comment]
I guess I'll take a look, but, uh, don't do that?

**Comment by ThePooN** [comment]
Why not? I regularly edit my settings, depending on what game I play. I set very low buffer when playing rhythm games (which tends to not be stable and often require a restart), and a higher one for anything else.

**Comment by crmarsh** [comment]
You probably didn't make said rhythm game, but I'll complain to you anyhow: the correct way to sync audio, video and input is not to do everything as fast as you can and pray.

**Comment by ThePooN** [comment]
You're right, which is why the offset exists. However, the hitsounds only play when I tap, and there's no way to resolve that with an offset.

**Comment by SwooshyCueb** [comment]
Can confirm this bug still exists

**Comment by crmarsh** [comment]
I saw this the other day in the debugger and I have a fix. FWIW, everything that uses WebRTC should have this bug.

I know what's going wrong with #16 now too, but it's a less trivial fix...

**Comment by crmarsh** [comment]
Should be fixed in 0.0.9
