### ISSUE TITLE
Download link https://discordapp.com/api/download/canary?platform=linux&format=tar.gz broken when using wget

### ISSUE THREAD

**Issue by JonasT** [crmarsh/discord-linux-bugs#51]
Try this:
```
wget https://discordapp.com/api/download/canary?platform=linux&format=tar.gz
mv canary\?platform\=linux canary.tar.gz
tar -xvzf canary.tar.gz
```
It will download 30MB, seemingly actually getting the application.
However, the result when trying to open it:
```

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I don't know how you managed to misconfigure the webserver so weirdly, but you should fix it..
It works fine when downloading directly in the web browser.

**Comment by crmarsh** [comment]
try
`wget https://discordapp.com/api/download/canary?platform=linux\&format=tar.gz`

You need to escape & characters in bash.

But yeah, I should probably make it suggest a better filename or something.

**Comment by JonasT** [comment]
If the URL is wrong, why wouldn't it give a 404 or similar? Instead it downloads 30MB of... something. That seems bugged

**Comment by crmarsh** [comment]
The URL is the one for the deb file.

**Comment by JonasT** [comment]
Ah ok. Sorry for bringing this up here, but: is there also a bugtracker for the other discord platforms? I found a notable bug in the web variant...

**Comment by crmarsh** [comment]
There is not, but you can just post it here I guess. Or email support, or chat with us in [Discord Devs](https://discord.gg/0ESuwoZe4M3ND6nb) server.
