### ISSUE TITLE
[KDE Plasma 5] Double clicking tray icon doesn't open Discord window.

### ISSUE THREAD

**Issue by Okramto** [crmarsh/discord-linux-bugs#52]
Once closed to tray, double clicking Discord's icon will not open its window. However right click > Open DiscordCanary still works.

Not a serious issue but double clicking is slightly more efficient than the context menu- that, and double clicking to open works in Cinnamon so I assumed it was the intended behavior.

    DiscordCanary: 0.0.8
    Distribution: Manjaro
    Kernel: 4.4.11-1
    KDE: 5.6.4
    64-bit

**Comment by Jibodeah** [comment]
I'm also using KDE Plasma 5 and double clicking on the system tray icon does open Discord for me.

```
DiscordCanary: 0.0.8
Distribution: Fedora 23
Kernel: 4.5.5-201
KDE Plasma: 5.6.4
KDE Frameworks: 5.22.0
64-bit
```

**Comment by Okramto** [comment]
I updated my kernel to the same version you're on, but I'm still unable to open on double click. The only other difference between our systems seems to be our distribution.

**Comment by crmarsh** [comment]
The [API](https://github.com/electron/electron/blob/master/docs/api/tray.md) claims that it doesn't work on Linux; it's why I added the "Open" option to the right click menu.

**Comment by ShayBox** [comment]
Not working for me also, i've seen things like Qjoypad double clicking work fine

**Comment by crmarsh** [comment]
I'm not claiming that other things don't support it, just that the lib we use doesn't.

**Comment by jrmiller82** [comment]
So... this was a "won't fix?" Your lib is broken if you can't click on a tray icon to open it...

**Comment by ShayBox** [comment]
Agreed, very needed if the windows and mac version has it. doesn't need to be a doubleclick, maybe a single click like the previously mentioned, but some sort of left click action.
