### ISSUE TITLE
Please offer account deletion

### ISSUE THREAD

**Issue by JonasT** [crmarsh/discord-linux-bugs#53]
The whole account deletion support article seems to be written in a way that fails to acknowledge it is simply not possible: https://support.discordapp.com/hc/en-us/articles/212500837-How-do-I-permanently-delete-my-account-

Of course your support article wants us to believe deletion isn't really needed, but that is wrong for many reasons:

**1. It is impossible to remove the associated e-mail from the account.** I tried. However, @spambog.com and other throw-away addresses don't work. Invalid e-mail addresses don't work. Possibly existing ones do, but then someone can sign up for them and get into my account. Why is removal of my associated e-mail important anyway? Simple: Patreon got hacked, Valve's Steam got hacked, LinkedIn got hacked, .... forcing a user to leave their e-mail address with you after they felt like leaving is a liability, because no service is ever fully safe from hacks.

**2. I can only make the service forget my password by entering another one.** This is a similar problem like above. Everyone gets hacked at some point. Your database might be hashed, but even if you did that it offers a data mark for guessing the password more easily. If you don't allow people who want to leave and move on to something else to wipe their account with their login password, you're increasing their security risk simply for some silly refusal to offer proper account deletion.

**3. Others can hack my account and impersonate me.** Since I cannot truly disable the login, if someone manages to get in for whatever reason (my password was simple enough for guessing, they got control over the e-mail address, ...) I'm opening up myself to identity theft.

You claim to be a secure choice. Then you should be easily able to acknowledge that identity theft and increasing possible exposure to hackers of your data is a *real threat*. Therefore, you shouldn't force us to give up control over the very central account data (e-mail, password) when we want to leave, and **offer a proper deletion**.

**Comment by crmarsh** [comment]
Our [feedback site](https://feedback.discordapp.com/forums/326712-discord-dream-land) is better for feature requests than this Linux bug tracker :-)

**Comment by JonasT** [comment]
This is already on the feedback site with pretty much no votes: https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/13491225-be-able-to-delete-your-account

However, you can see from the comments here that other people are definitely unhappy with this as well, and probably just didn't find the feedback forum entry: https://support.discordapp.com/hc/en-us/articles/212500837-How-do-I-permanently-delete-my-account-

Also I don't think the average user understands the security implications. However, should that mean it's not provided for those who do?

**Comment by crmarsh** [comment]
Everything starts with pretty much no votes :-p

I'm not claiming we won't or shouldn't add this, I was just pointing out that the feedback site is our mechanism for this kind of feedback.

**Comment by JonasT** [comment]
Now the feedback idea was even deleted for some reason. For a service that uses "secure" in its advertising, you sure don't seem to care much about basic common sense measures to minimize risk of a data breach. Shameful.

**Comment by crmarsh** [comment]
Huh, I dunno why it was deleted, but it looks like there are others with the same request, maybe just vote one of those up?
