### ISSUE TITLE
Support suggests "hunting down for APKs", completely fails to acknowledge how unsafe that is even when it is pointed out

### ISSUE THREAD

**Issue by JonasT** [crmarsh/discord-linux-bugs#54]
Some people have phones with no Google Play store. (e.g. Amazon devices, or when running Cyanogenmod with no Google Services motivated by privacy concerns) Since I am one of them, I thought why not ask the support if there is a discord APK available for install without the use of the Google Play store.

Support response:
```
Hey Jonas!

While we cannot officially recommend using .apk files to side load Discord, you can do a little hunting around the web and find something of your interest. Let me know if you have any other questions or concerns and I'll try my best to answer them for you!

Thanks,
```
As you can see, the support completely fails to acknowledge how **inherently insecure** that is. To make it more obvious, let me rewrite this support response for Microsoft Windows: "While we cannot officially recommend using .exe files to side load Discord, you can do a little hunting around the web and find something of your interest."
Really?? Searching random executables from random sources? That sure sounds like a splendid idea...

When I pointed it out in a response mail that this shouldn't be recommended to anyone ever, unless it was accompanied with a very big note how insecure that practice can be, it was ignored.
When I pointed this out to twitter, the person responding also failed to get the point: https://twitter.com/T_i_Jones/status/738138172723367936

Therefore I am bringing it up here, in the hope that your support staff will be made aware of this issue and hopefully improve more in the line of the "secure" promise of your product.

**Comment by crmarsh** [comment]
I passed your note on to the support folks. Also, we were meaning to update our build to upload the apks to our own CDN at some point, just have not gotten around to it yet.

Thanks :-)

**Comment by JonasT** [comment]
Well support claims this is not gonna happen:
```
2) We'll have Discord on the Kindle app store at some point, but have no plans to go the route of having an official APK, sorry.
```
(this was actually sent to me per e-mail as a response)

Sorry if I don't hold my breath until I actually see the APK links on your site... or you at least fix the web interface for mobile as described in the other ticket.
