### ISSUE TITLE
Web interface is broken on mobile due to incomplete "viewport" usage

### ISSUE THREAD

**Issue by JonasT** [crmarsh/discord-linux-bugs#55]
The web interface is broken on mobile due to incomplete "viewport" usage:

The web interface seems to work almost perfectly fine even in a mobile browser, and it would be nicely usable with a bit of zooming around - if the "viewport" header info (in the HTML ```<head>```) hadn't disabled zooming *without at the same time specifying a sensible minimum page size for discord to work properly*. As a result, I'm seeing a super squeezed version of discord at regular zoom where all UI elements intrude each other and which is unusable, and I can't somehow zoom out or in either to make enough space for the UI to work because it was disabled.

Why fix it since you have a mobile app? The app can do inherently more bad things on a phone, so some people might prefer a web interface, even if it's a little clumsy to use on mobile. Also, as pointed out above it should be a trivial one-line fix. Also, the app is only available through Google Play store as of now, which not every Android phone is equipped with.

**Comment by crmarsh** [comment]
I think we'd rather fix apk distribution than try to support mobile browsers.

**Comment by JonasT** [comment]
In case you change your mind, this CSS fixes it:
(It also fixes running discord in a small window on desktop, so it's not even purely a fix for mobile)

```css
    body {
        overflow: auto;
    }
    #app-mount .app {
        min-width:800px;
        min-height:600px;
    }
```
