### ISSUE TITLE
Minimized at startup

### ISSUE THREAD

**Issue by HorlogeSkynet** [crmarsh/discord-linux-bugs#57]
Hello there !

I've installed yesterday this build, and it works like a charm ! Thanks for the development :smile: 

I've got a question, is it possible to get an option in the next version to choose if we want or not the client minimized at startup. Because once the system has boot, I got the Discord window wide-open !

Thanks !

**Comment by crmarsh** [comment]
Yeah, I'll try to revise that stuff across platforms.

**Comment by HorlogeSkynet** [comment]
Hey,

Is this added to an intern milestone, or not ?

Thx !

**Comment by HorlogeSkynet** [comment]
I assume no then, closing here.
