### ISSUE TITLE
All messages show incorrect time sent.

### ISSUE THREAD

**Issue by MrKrucible** [crmarsh/discord-linux-bugs#59]
All messages on Discord are 7 hours ahead of my PDT time. I have a fresh install of Arch Linux and I've properly set up my systems locale settings. This issues also persists on any web version of Discord I use on my system as well. How can I have Discord recognize the correct time?

**Comment by crmarsh** [comment]
Are you sure this has anything to do with Discord? Try out [an online clock](http://onlineclock.net/) in your browser -- does it also show the wrong time?
