### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by dpeukert** [crmarsh/discord-linux-bugs#6]
Report from 0.0.1

![memoryleak](https://cloud.githubusercontent.com/assets/3451904/14648352/265f15f6-0662-11e6-94cf-42e8c72dd705.png)

**Comment by crmarsh** [comment]
0.0.2 is based on electron 0.37.6, the release notes of which say "Fix idle GC not working in the main process." -- wonder if that is related.

**Comment by MrDetonia** [comment]
Do we have access to earlier versions of the Canary to compare?

**Comment by crmarsh** [comment]
I'm not seeing this on any of the last few builds, so I'm gonna close this.
