### ISSUE TITLE
Everyone appears white with compact theme, links have no context menu.

### ISSUE THREAD

**Issue by Mikachu** [crmarsh/discord-linux-bugs#61]
This used to work in the current 0.0.8 version but started happening 2 or 3 days ago. At the same time, right clicking on links started having the "copy link" and "open link" entries, resulting in no menu at all showing up if there is no selected text. Nothing on my end changed so I guess parts of the interface is loaded from the servers on startup. Changing to Cozy fixes the color issue but not the link issue. Restarting the app doesn't help, but using discord from the website everything is as normal. I also have access to "Pinned messages" which it seems nobody else does that I've asked?

**Comment by Mikachu** [comment]
https://canary.discordapp.com/assets/d98158f5ce2e2dd38871.css seems to have a rule to make the color for .theme-dark .message-group.compact .user-name { color: #f9f9f9!important; } which overrides the element color for the role.

**Comment by crmarsh** [comment]
This was fixed pretty quick, sorry I forgot to reply here until now.
