### ISSUE TITLE
discord ignore DISPLAY varible

### ISSUE THREAD

**Issue by MEXAHOTABOP** [crmarsh/discord-linux-bugs#62]
i have two monitor configuration with ZaphodHeads (separate X screen for each monitor)
when i run discord with DISPLAY=:0.1 i get discord on display 0.0

**Comment by crmarsh** [comment]
I'm not clear if this is a bug or missing feature; I'm certainly not doing anything with the DISPLAY variable, it must be something from electron.

**Comment by MEXAHOTABOP** [comment]
i checked discord now 
i have many changes in system from this time and not sure changed something in discord or on my local machine but seems all work properly now

sorry for the long delay
