### ISSUE TITLE
Tray icon missing

### ISSUE THREAD

**Issue by ultimate255** [crmarsh/discord-linux-bugs#65]
Discord tray icon missing on the Wingpanel

Elementary OS 0.3.2 Freya
Pantheon Desktop

**Comment by GreyAsteroid** [comment]
Duplicate of https://github.com/crmarsh/discord-linux-bugs/issues/4

It's a problem with electron that can be tracked here https://github.com/electron/electron/issues/5050

Can be worked around by launching with the environment set to Unity
`env XDG_CURRENT_DESKTOP=Unity /usr/share/discord-canary/DiscordCanary`
