### ISSUE TITLE
Linking to YouTube & Twitch doesn't work

### ISSUE THREAD

**Issue by GhostSquad57** [crmarsh/discord-linux-bugs#67]
Hello! I found a bug with Discord Canary for Linux.

When trying to link Discord with my YouTube or Twitch account, I get an error:

`Error: redirect_uri_mismatch`

-Arch Linux with latest updates

**Comment by crmarsh** [comment]
Yeah, this is just not set up to work from the canary or ptb builds on any platform; you'll need to use the web version to set up those connections.
