### ISSUE TITLE
Game detection

### ISSUE THREAD

**Issue by dpeukert** [crmarsh/discord-linux-bugs#7]
...is not yet implemented

**Comment by crmarsh** [comment]
It is in progress, other stuff keeps coming up ¯\\\_(ツ)\_/¯

**Comment by dpeukert** [comment]
Yep, I know, I just wanted to submit an issue so that people can subscribe :+1: 
Thanks for you work on the Linux version

**Comment by dpeukert** [comment]
Initial version of game detection is in 0.0.4 :clap:

**Comment by crmarsh** [comment]
Yup, fixed in 0.0.4
