### ISSUE TITLE
Notification audio

### ISSUE THREAD

**Issue by wobbol** [crmarsh/discord-linux-bugs#74]
I am using Debian Jessie x86_64 with gnome3

Discord Canary plays audio when the Notification test button is clicked in settings, but the notification sound does not play when an event happens.

**Comment by crmarsh** [comment]
Our next js update should change how the audio stuff works, hopefully the new version will fix this for you.

**Comment by wobbol** [comment]
It works for me right now. If the changes were pushed :+1: close this if you want,
else 
it's an intermittent bug.

**Comment by crmarsh** [comment]
Yup, new version is pushed, glad it's working :-)
