### ISSUE TITLE
Default Input Volume Too High (25700%) - Discord Canary 0.0.8-1 -  Manjaro Linux 16.06.1

### ISSUE THREAD

**Issue by StewieFellows** [crmarsh/discord-linux-bugs#75]
When changing my input device to an M-Audio Fast Track DAC, the input volume always jumps to 25700%. I can use the horizontal scrollbar to go all the way to the right and see the handle for the volume, which I can hover over to see 25700% and can be dragged to the left to fix the volume level. The bug is repeatable if the device is selected from the dropdown again. I've seen this bug mentioned on the Discord Canary Reddit, but they've stated it was fixed in 0.0.1.

Note: Based on my experience with this issue, Discord still seems to treat the actual mic volume in voice chat as 100% even when set to something greater, so it may only affect the UI.

Versions of the software used are in the title. Please let me know if any more information is needed.

Screenshots:

![screenshot_2016-08-12_21-12-11](https://cloud.githubusercontent.com/assets/20199036/17640837/4808c808-60d7-11e6-9dd5-ca21d52bb026.jpg)
![screenshot_2016-08-12_21-14-11](https://cloud.githubusercontent.com/assets/20199036/17640838/50f875ee-60d7-11e6-8cc6-fbde8f3bfcb8.jpg)

**Comment by tkdberger** [comment]
Might I suggest (keyword suggest) reinstalling the package? Some problems sorta magically vanish after doing that.

**Comment by greenbigfrog** [comment]
This has been fixed like years ago...

**Comment by StewieFellows** [comment]
Ok, I'll try reinstalling, and I'll delete the profile data to see if rebuilding it from scratch fixes it.

**Comment by skwerlman** [comment]
Which audio back end are you using? ALSA or Pulse Audio?

**Comment by StewieFellows** [comment]
I'm using Pulse Audio.

**Comment by smilzoboboz** [comment]
I'm experiencing the same issue.
My machine setup:
ArchLinux (rolling)
Pulseaudio 9.0
XFCE 4.12
Double sound card:
- nVidia GPU sound-card (output only, system default for output)
- integrated (I/O, system default for input), discord runs on integrated for both input and output

Using the "default" input device in discord I get 0% volume, which I can set up to 100% but the mic is not active (I guess it points to the default output sound-card instead of input one).
Using the integrated sound-card the volume spikes to 25700%.

**Comment by crmarsh** [comment]
I see the bug here; we're checking for the max volume of the device, but only once on startup rather than on device change. So if the first thing has a max volume of 0xff, then the next device has a 2 byte scale, then 100% turns into 25500%

**Comment by StewieFellows** [comment]
Thank you for the update Chris!

**Comment by arcooke** [comment]
Not sure if an update has been pushed out for this yet, but I experienced something that might be related yesterday.  Everything was fine, and then a user in my server said my volume got insanely loud and he had to turn me down to "like 3%".  

I was unaware of this bug report so I didn't think to check there.. but I will keep an eye out if it happens again.

I'm on KDE Neon

**Comment by ahjolinna** [comment]
it would be nice if discord could force max input to be "inside" the 100%, when at least in kde you "override" the volume to max 150%, it looks so stupid/wierd on discord settings when the input audio is over 100%: 
![spectacle zt9150](https://cloud.githubusercontent.com/assets/6993072/20035156/4570c8e6-a3e1-11e6-8334-fcffce599dcf.png)

@arcooke : I would use the "automatic input sensitivity" thingy, so there is no need to manually adjust the input volume (I would also check/enable stuff in advanced option)

**Comment by StewieFellows** [comment]
@ahjolinna That settings doesn't affect your input volume. That setting only controls how much input needs to be detected in order for Discord to begin transmitting.

**Comment by crmarsh** [comment]
I think this is fixed in 0.0.11

**Comment by StewieFellows** [comment]
Fixed for me. Thanks for the help!
