### ISSUE TITLE
Channel List does not appear properly

### ISSUE THREAD

**Issue by gourdcaptain** [crmarsh/discord-linux-bugs#76]
Starting today (8-12-16), using the official client on Arch Linux (v.0.0.8) doesn't show my list of channels on my server:
https://www.dropbox.com/s/rb2qi18ttx392kl/Discord-Official-BrokenChannels.jpg?dl=0

They display properly in Chromium, Firefox, and the old unofficial Discord electron client:
https://www.dropbox.com/s/ravupkg8s2ih1h1/Discord-Unofficial-Channels.jpg?dl=0

I am using Arch Linux, XFCE4 desktop, and the xf86-video-intel graphics drivers.

EDIT: On the other server I have access to (which is much smaller in terms of channel count) the two channels display properly.

Edit2: I have tried deleting the configfolders to no effect. The rest of the windows displays properly, but the options are not invisible - clicking where they would be has no effect.

**Comment by ddlr** [comment]
I’m using Arch Linux and xf86-video-intel drivers as well, but I’m using the i3 window manager. I can confirm that this is also a problem for me and that the bug doesn’t appear in the browser version.

For me, when I click from a server to Direct Messages and back, the “Text Channels” and “Voice Channels” lists disappear.

These actions appear to restore the lists: clicking on another server, disconnecting from a voice channel, opening the hamburger menu of a server, muting a channel’s notifications, muting the microphone, and opening the console via Ctrl-Shift-I.

Video:
https://gfycat.com/BabyishLavishFulmar

Screenshots:
Channel list disappeared - https://lambda.sx/XUp.png
Channel list restored - https://lambda.sx/mhs.png

**Comment by AshishBhattarai** [comment]
I'm using Arch Linux and having same issues. When the Text Channels and Voice Channels lists reappear i cannot scroll through them.

**Comment by ddlr** [comment]
@AshishBhattarai I think you’re looking for #77, though these two issues may be related.

**Comment by SolarPolarMan** [comment]
I have this but on eOS (Ubuntu 14.04)

**Comment by ZZIIKKemd** [comment]
Same thing on Linux Mint 17.3 KDE version.

**Comment by crmarsh** [comment]
Our brilliant CSS minds will need to take a look at this one, I've passed along the report.

**Comment by Serkan-devel** [comment]
I'm facing the same problem. But it sometimes randomly re-appears when switching channels. But not completely. 
![bildschirmfoto931](https://cloud.githubusercontent.com/assets/16866642/17647912/b8066ba0-6204-11e6-960a-5e6bb13981e8.png)

**Comment by greenbigfrog** [comment]
similar: 
![image](https://cloud.githubusercontent.com/assets/6208894/17649372/6805a2da-6234-11e6-9968-16604b24a851.png)

(This happens on the friends list)

**Comment by gourdcaptain** [comment]
This has resolved itself for me at least around 9 PM on 8/14/16.

**Comment by SolarPolarMan** [comment]
Fixed for me too :D
