### ISSUE TITLE
Cannot scroll channel list

### ISSUE THREAD

**Issue by blha303** [crmarsh/discord-linux-bugs#77]
I'm on a server with lots of text channels and probably the same number of voice channels. The scroll wheel doesn't scroll the channel list, and no scrollbar appears, so it's impossible to access the rest of the channel list.

Ubuntu MATE 16.04, Metacity compositor

**Comment by Xtrinity** [comment]
Yup, same here. Just started happening for me as well

**Comment by Xtrinity** [comment]
I found a temporary fix.
Press Ctrl+Shift+I and then open the elements panel until you find `<div class="guild-channels">`. Click on the element and change the CSS styling from `overflow: hidden` to `overflow:scroll`

**Comment by blha303** [comment]
Good find :D A better fix would be to set `overflow-y`, or run this in Console: `$(".guild-channels").style.overflowY = "scroll"`

**Comment by ddlr** [comment]
Can confirm (Arch Linux, i3 window manager).

**Comment by TheBlackParrot** [comment]
happening here in Arch with Mutter too

**Comment by yeltsin** [comment]
Happening here too. I'm using Ubuntu 16.04.

**Comment by Erenzie** [comment]
Happening for me as well (Arch, xfce). The temporary workaround won't work for me either - just opens a white empty panel on the side of the window when I press Ctrl+Shift+I.

**Comment by Serkan-devel** [comment]
Having the same problems on Kubuntu 16.04

**Comment by perkkie** [comment]
Been having the same problem, though the workarounds here won't work for me. The element mentioned is missing, and when I type the console command it returns this: "Uncaught TypeError: Cannot read property 'style' of null (VM2055:2)".

**Comment by ddlr** [comment]
Looks like it’s fixed on my end.

![2016-08-15-181417_236x603_scrot](https://cloud.githubusercontent.com/assets/2908767/17657043/45cd3184-6314-11e6-88f3-e47354db0fee.png)

**Comment by blha303** [comment]
Fixed in issue #76
