### ISSUE TITLE
Stuck on "checking for updates" prompt

### ISSUE THREAD

**Issue by pingex** [crmarsh/discord-linux-bugs#8]
I'm on Linux Mint 17.3, Discord is stuck on checking for updates, can't do anything except manually killing Canary.

Here's what I tried:
- purging/reinstalling the .deb file
- removing `~/.config/discord/`

Also worth mentioning (I guess): I did a Wireshark capture, saw HTTPS traffic to Discord go by (including TCP FIN), but couldn't get the encrypted content obviously. So network isn't the problem.

CLI output
```
$ discord-canary 
0: [+] Entered: WorkerThreadMain
0: [+] Entered: Initialize
0: [-] Exited: Initialize
Using update channel 'canary'
update: you are out of date! Latest: {"pub_date": "2016-04-19T07:47:58", "name": "0.0.2"}
update: you are out of date! Latest: {"pub_date": "2016-04-19T07:47:58", "name": "0.0.2"}
^C385656: [-] Exited: WorkerThreadMain
```

`uname -a`
```
Linux G551JW-Mint 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa
```

**Comment by crmarsh** [comment]
Fixed in 0.0.3
