### ISSUE TITLE
[BUG] (Ubuntu 16.04) "X" button only 'minimize' the application.

### ISSUE THREAD

**Issue by valrossenOliver** [crmarsh/discord-linux-bugs#80]
When pressing the red X button to close the application, the window closes but everything keeps running. I can talk and mute. Currently I think the application DOES quite if you in Discord go to the frame meny, press Edit -> Exit. But I've got no confirmation about the last statement.

Regards, Oliver Magnusson.

**Comment by crmarsh** [comment]
This is by design (and fairly common for communications programs); the tray icon should still be available to bring the window back, and yeah, the exit on the menu there really does exit (as does Ctrl-q). We're planning on adding more options around that stuff, but haven't gotten around to it yet.
