### ISSUE TITLE
Segmentation fault on different scenarios (network change, pulseaudio restart)

### ISSUE THREAD

**Issue by GhettoGirl** [crmarsh/discord-linux-bugs#82]
```
Arch Linux 64-bit
Linux 4.7.0
NetworkManager 1.4.1
PulseAudio 9.0
```

I found some really weird problems in the Discord app. First I wanna ask, **are there any native C++ addons in Discord Canary?** Otherwise a segmentation fault wouldn't make really much of a sense to me ─ correct me if I'm wrong.

The app crashes with a segmentation fault for me after the following scenarios happen:
 - **Network connection change** (connect/disconnect) while discord is running without having focus (in background?) </br>
   Doesn't happen when the app has actual focus and is being used :confused:
 - **PulseAudio server restart** </br>
   I don't use voice chat and have speakers/mic muted, if that makes a difference.

Really really weird is that the segmentation faults happen in the Electron renderer process (`DiscordCanary --type=renderer` in the process table) and not the main process. What I know is that the renderer process in the Chromium web engine. Maybe its an upstream bug? What version of Electron are you using? Have you tried updating to the latest version by simple repacking Discord. Wouldn't be that hard either and the app hadn't an update in years. Please try repacking with latest Electron. I pretty sure now that this is an upstream bug in Chromium which was maybe fixed a long time ago.

I'm having a hard time to debug this too. I'm not even sure if others have the same problem or if its just me.

**Comment by crmarsh** [comment]
Is this while connected to voice or not?

**Comment by GhettoGirl** [comment]
Nope, just text chat. I don' use voice chat so I'm not sure though.

**Comment by SwooshyCueb** [comment]
This doesn't happen for me. Also running Arch Linux, but with liquorix kernel 4.7.2. Are you using networkmanager?

**Comment by GhettoGirl** [comment]
Yes NetworkManager. I'm also getting segfaults when a connection is established, so when I start Discord and connect to the internet afterwards.

**Comment by GhettoGirl** [comment]
@crmarsh I updated the issue above. Please review if you have time. Thanks :)

**Comment by crmarsh** [comment]
PulseAudio crash (#50) I have a fix for, should be in next build.
We do have C++ addons (though the above crash was in WebRTC, not one of our modules).
I have not looked into the network change bug yet, but I will.

**Comment by crmarsh** [comment]
I tested out the network disconnect/reconnect thing and it seems to work correctly for me now; can you double check 0.0.9 and see if it is fixed for you?

**Comment by GhettoGirl** [comment]
There are no longer weird crashes on connectivity changes. Seems to be fixed now :)
