### ISSUE TITLE
X11 Clipboard pasting does not take files as it does on Windows.

### ISSUE THREAD

**Issue by Payden-Pringle** [crmarsh/discord-linux-bugs#85]
When I copy an image to the X11 clipboard (i.e. using xclip with `xclip -i < <file>.png`), then try and paste it to Discord, it comes out as a text representation of the file and not the file. As an example, try and open a .png in a text editor. That's what it comes out as.

My use case is that I screenshot to clipboard then paste to discord without creating image files and without needing to go into a file manager. It simplifies the process a lot and makes posting an image to discord from my screen nearly no effort. 

I very much enjoyed this feature (pasting a file from clipboard to Discord) on Windows, and would like it if it worked on Linux as well.

System info (if relevant):
4.7.1-1-ARCH x86_64 GNU/Linux
awesome 3.5.9-1 - Window Manager
X.Org X Server 1.18.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.5.4-1-ARCH x86_64
Current version of pixman: 0.34.0
xclip 0.12.git.20160201-1 - Command line interface to the X11 clipboard

I'm using a script for getting the image to the clipboard.

`import root <file>.png`
`xclip -i < <file>.png`
`rm <file>.png`

import is a function of imagemagick that lets you capture a display. Running it with root but not -window lets you select a portion of the screen.

**Comment by crmarsh** [comment]
Doing `xclip -i whatever.png` loads up the file as a string into the clipboard with type UTF8_STRING. If you were to set the type to image/png or something, it would work. `xclip -i whatever.png -t image/png` works fine for me.

**Comment by Payden-Pringle** [comment]
Well, I apologize. I should've RTFM. Thanks Chris.

**Comment by crmarsh** [comment]
np, glad it's working for you :-)
