### ISSUE TITLE
Append Channel Name to Application Title for the Window

### ISSUE THREAD

**Issue by erockce** [crmarsh/discord-linux-bugs#88]
The application's title says, "discord-canary-bugs" in the title bar.

The title used should minimally be the same as used in the context menu of the system tray icon.  In this current build, the tooltip of the system tray icon says "DiscordCanary".  As the application matures, the title could be renamed to just "Discord" or "Discord for Linux".

Package: discord-canary-0.0.8:amd64
Kernel: 4.4.0-36-generic x86_64 (64 bit)
Desktop: Cinnamon 3.0.7
Distro: Ubuntu 16.04 xenial

![discordlinux-wrong-title](https://cloud.githubusercontent.com/assets/17682973/18229118/79232a8c-7220-11e6-8513-db71bad18d51.jpg)

**Comment by erockce** [comment]
Ok, the title was dependent on the channel I was in at the time.  I logged out and at the login screen the title was "Discord".  I think however that after logging in and going to a channel, the title should be "Discord - <name of current channel>".

**Comment by crmarsh** [comment]
Hmm, I fixed that once but it looks like it got reverted. I'll investigate.

**Comment by crmarsh** [comment]
I added a " - Discord" to the window title.
