### ISSUE TITLE
Text Size On 4k Resolution

### ISSUE THREAD

**Issue by zeeshan595** [crmarsh/discord-linux-bugs#90]
Hey I have searched everywhere on the settings to increase text size in 4k the text is so small and difficult to read. It would be nice to have a slider which increases the text size.

**Comment by crmarsh** [comment]
That would be a good addition; but just a suggestion: setting this per app sounds kinda crazy; I think what you want is to [configure scaling more system wide](https://wiki.archlinux.org/index.php/HiDPI).

**Comment by zeeshan595** [comment]
You have a very good point but and on my system settings I have scaled up everything by 1.25 but some apps still don't follow that sadly. Normally everything on terminal or nautilus is looking fine its just a few apps that aren't compatible.
