### ISSUE TITLE
no audio in linux canary app

### ISSUE THREAD

**Issue by gnowxilef** [crmarsh/discord-linux-bugs#95]
for some reason, the audio does not work anymore for the linux canary app. it was working for some time and then just stopped. restarting the app multiple times did not fix the issue. (and, yes, audio works for all other applications. e.g. chrome/firefox/skype/etc.). this happens for all servers.

i would provide logs, but no idea where they are.

**Comment by skwerlman** [comment]
Are you using ALSA or Pulse?

**Comment by gnowxilef** [comment]
i am using pulse.

**Comment by AstralStorm** [comment]
Same issue here, except it never worked in 0.0.8. Audio is fine in chromium web client.
The funny part is that notifications play all right.

**Comment by crmarsh** [comment]
It there anything interesting on the [audio debug panel?](https://support.discordapp.com/hc/en-us/articles/216600077-Voice-Debug-Central)

**Comment by gnowxilef** [comment]
afaict, nothing really of interest. other than "check unknown sources" showing that i am receiving packets from unknown source.

**Comment by gnowxilef** [comment]
attaching logs as well.

[zxcvzxcv.txt](https://github.com/crmarsh/discord-linux-bugs/files/523131/zxcvzxcv.txt)

**Comment by gnowxilef** [comment]
there are, however, a bunch of diagnostics that are question marks, showing "no diagnostics ran"

**Comment by gnowxilef** [comment]
i forgot to add that using the web ui works just fine. only the canary app has no sound.

**Comment by AstralStorm** [comment]
Seems fixed in release 0.0.9.
