### ISSUE TITLE
Global hotkeys issue

### ISSUE THREAD

**Issue by Victu** [crmarsh/discord-linux-bugs#96]
I found a problem with Canary 0.0.8 version on my OpenSUSE Tumbleweed.
The problem is if i set 2 global hotkeys actions on one key with different modificators, let's say left_ctrl+left_meta+f and left_meta+f, then both actions will fire if i press left_ctrl+left_meta+f. But it is expected that only one action, which was binded on left_ctrl+left_meta+f, will be triggered when  left_ctrl+left_meta+f is pressed.

**Comment by crmarsh** [comment]
The way this is written at the moment the different hotkeys don't know about each other in a way that would make this work (ABC would suppress AB). I'm a little uncertain at the moment but this seems like it would add more problems than it is worth as a feature. We have a fairly limited set of things that can be globally bound, and even fewer than any particular person uses regularly, so finding a couple of distinct key combos should not be too challenging.
