### ISSUE TITLE
Error 502 from CloudFlare

### ISSUE THREAD

**Issue by skwerlman** [crmarsh/discord-linux-bugs#98]
(That window is in fact discord, and not a normal browser.)
![image](https://cloud.githubusercontent.com/assets/6954107/19370235/95a0a5d2-9178-11e6-87d1-6dd3ce18dd0c.png)

**Comment by crmarsh** [comment]
Yeah, our server folks are [having a bad day](https://twitter.com/discordapp/status/786707154376003585). It's not really a client bug -- though I suppose you could argue that we should catch that and display a better error...

**Comment by skwerlman** [comment]
Better handling of this would be nice, esp since errors with Google are pretty far out of your control.
