### ISSUE TITLE
[Gnome 3 | Arch] Window controls incomplete

### ISSUE THREAD

**Issue by sn0w** [crmarsh/discord-linux-bugs#99]
The window only has a close button on Arch Linux / Gnome 3.
Is this a known bug (i.e. does anyone know how to fix it)?
On Ubuntu / Unity 7 it worked just fine. 

Thanks in advance :)

<hr>

Screenshot:
![screenshot from 2016-10-19 00-03-34_censored](https://cloud.githubusercontent.com/assets/5665732/19498268/418b7df2-9590-11e6-8d5a-a25be21b2bf0.jpg)

**Comment by crmarsh** [comment]
Weird, I don't do anything special to override those.
